//! The `explain_config_option` tool: describes one option of `mirrord.json` or `mirrord-up.yaml`
//! from the config schema compiled into this binary, so an agent doesn't have to read the whole
//! schema or guess.
//!
//! The schema is generated by schemars, so an option's schema is rarely a plain object: optional
//! fields are an `anyOf` with `null`, many options accept a short form (a bool or a string) next
//! to the full object, and types are shared through `$ref`s. A path is resolved by following every
//! branch at once, and what is reported about an option is gathered from all of its branches.
//!
//! The plan an option needs comes from the schema's [`PLAN_ANNOTATION`]s, which an option inherits
//! from the options and types above it. Where the alternatives of an option need different plans,
//! such as the target kinds of `target.path`, each alternative's plan is reported as well.

use std::{collections::HashSet, ops::Not, sync::LazyLock};

use mirrord_up::LAYER_CONFIG_PATHS;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use thiserror::Error;

use crate::{
    schema::{LAYER_SCHEMA, UP_SCHEMA},
    tools::validate_config::ConfigFormat,
};

/// Schema annotation naming the [`Plan`] an option needs. Options without it inherit it from the
/// closest annotated option above them.
const PLAN_ANNOTATION: &str = "x-mirrord-plan";

/// Stands for any key of a map (such as a service name) in the paths suggested for an unknown one.
const ANY_KEY: &str = "<name>";

/// How many paths are suggested for an unknown one.
const SUGGESTIONS: usize = 5;

#[derive(Debug, Deserialize, JsonSchema)]
pub struct ExplainConfigOptionArgs {
    /// Dotted path of the option, e.g. `feature.network.incoming.mode` in a `mirrord.json`, or
    /// `services.api.http_filter.header_filter` in a `mirrord-up.yaml`.
    pub path: String,
    /// Which config file the option is in. Defaults to `mirrord.json`.
    #[serde(default)]
    pub format: Option<ConfigFormat>,
}

#[derive(Debug, Default, Serialize, JsonSchema)]
pub struct ExplainConfigOptionOutput {
    /// Whether the option exists. When it doesn't, `suggestions` lists the closest known options
    /// and nothing else is set.
    pub found: bool,
    /// What the option does.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The JSON types the option accepts, e.g. `["boolean", "object"]` for an option that can be
    /// toggled or configured in detail.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub types: Option<Vec<JsonType>>,
    /// The values the option accepts, when the schema enumerates them.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub allowed_values: Option<Vec<Value>>,
    /// The value used when the option is not set, when the schema declares it.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default: Option<Value>,
    /// The cheapest mirrord plan the option can be used with. Always set for a known option.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plan: Option<Plan>,
    /// The plan each alternative form of the option needs, when they differ, e.g. the target
    /// kinds `target.path` accepts.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plan_by_alternative: Option<Vec<AlternativePlan>>,
    /// For a `mirrord-up.yaml` option, the `mirrord.json` option it sets in the config `mirrord
    /// up` generates for each service.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mirrord_json_path: Option<String>,
    /// For an unknown option, the closest known ones, with `<name>` standing for any map key such
    /// as a service name.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub suggestions: Option<Vec<String>>,
}

/// A JSON Schema `type`. `null` is left out: nearly every option is optional, so it would be
/// listed for almost all of them without telling anything about the option.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum JsonType {
    Boolean,
    Integer,
    Number,
    String,
    Array,
    Object,
}

impl JsonType {
    /// The type of `value`, a number being a `Number` even when it is an integer.
    fn of(value: &Value) -> Option<Self> {
        match value {
            Value::Bool(_) => Some(Self::Boolean),
            Value::Number(_) => Some(Self::Number),
            Value::String(_) => Some(Self::String),
            Value::Array(_) => Some(Self::Array),
            Value::Object(_) => Some(Self::Object),
            Value::Null => None,
        }
    }
}

/// The mirrord plans (<https://metalbear.com/mirrord/pricing/>), cheapest first.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, JsonSchema,
)]
#[serde(rename_all = "lowercase")]
pub enum Plan {
    /// Free, open source mirrord.
    Oss,
    /// mirrord for Teams, which comes with the mirrord Operator.
    Team,
    Enterprise,
    /// This mirrord version doesn't record the plan the option needs.
    #[serde(skip_deserializing)]
    Unverified,
}

/// The plan one alternative form of an option needs.
#[derive(Debug, PartialEq, Serialize, JsonSchema)]
pub struct AlternativePlan {
    /// The alternative: its value for one of a set of values, or the field that tells it apart
    /// for one of a set of objects (e.g. `job` for a job target).
    pub alternative: String,
    pub plan: Plan,
}

#[derive(Debug, Error)]
pub enum ExplainConfigOptionError {
    #[error("the option path is empty")]
    EmptyPath,
}

/// Every option path of each schema, to suggest from.
static LAYER_PATHS: LazyLock<Vec<String>> = LazyLock::new(|| known_paths(&LAYER_SCHEMA.raw));
static UP_PATHS: LazyLock<Vec<String>> = LazyLock::new(|| known_paths(&UP_SCHEMA.raw));

pub fn explain_config_option(
    ExplainConfigOptionArgs { path, format }: ExplainConfigOptionArgs,
) -> Result<ExplainConfigOptionOutput, ExplainConfigOptionError> {
    let segments: Vec<&str> = path.trim().split('.').collect();
    if segments.iter().all(|segment| segment.is_empty()) {
        return Err(ExplainConfigOptionError::EmptyPath);
    }

    let (explained, known) = match format.unwrap_or(ConfigFormat::MirrordJson) {
        ConfigFormat::MirrordJson => (
            explain(&LAYER_SCHEMA.raw, &segments),
            LAYER_PATHS.as_slice(),
        ),
        ConfigFormat::MirrordUpYaml => (explain_up(&segments), UP_PATHS.as_slice()),
    };

    Ok(explained.unwrap_or_else(|| {
        let mut suggestions = suggestions(&segments, known);
        // A `mirrord.json` option is set for a service through the `mirrord-up.yaml` setting
        // that maps onto it, or else through the service's `config_patch`.
        if format == Some(ConfigFormat::MirrordUpYaml)
            && explain(&LAYER_SCHEMA.raw, &segments).is_some()
        {
            let asked = segments.join(".");
            let mut up_paths: Vec<String> = LAYER_CONFIG_PATHS
                .iter()
                .filter(|(up_path, _)| up_path.starts_with("services.*."))
                .filter_map(|(up_path, layer_path)| {
                    let rest = match asked.strip_prefix(layer_path)? {
                        "" => "",
                        rest => rest.strip_prefix('.').map(|_| rest)?,
                    };
                    (layer_path.is_empty().not())
                        .then(|| format!("{}{rest}", up_path.replace('*', ANY_KEY)))
                })
                .collect();
            up_paths.push(format!("services.{ANY_KEY}.config_patch.{asked}"));
            suggestions.retain(|suggestion| up_paths.contains(suggestion).not());
            suggestions.splice(0..0, up_paths);
            suggestions.truncate(SUGGESTIONS);
        }
        ExplainConfigOptionOutput {
            suggestions: Some(suggestions),
            ..Default::default()
        }
    }))
}

/// Explains a `mirrord-up.yaml` option from its own schema, completed with what the
/// `mirrord.json` option it maps onto says. Settings shared with `mirrord.json` have their docs
/// written there, and a `config_patch` has no schema of its own.
///
/// Outside a `config_patch`, an option the up schema doesn't have doesn't exist, even where the
/// `mirrord.json` option it would map onto does: up settings can take another shape, e.g. a
/// service's `target` holds a `path` rather than the target itself.
fn explain_up(segments: &[&str]) -> Option<ExplainConfigOptionOutput> {
    let mirrord_json_path = layer_config_path(segments);
    let in_config_patch =
        layer_config_mapping(segments).is_some_and(|(layer_path, _)| layer_path.is_empty());
    let layer = mirrord_json_path.as_ref().and_then(|path| {
        let segments: Vec<&str> = path.split('.').collect();
        explain(&LAYER_SCHEMA.raw, &segments)
    });

    let output = match (explain(&UP_SCHEMA.raw, segments), layer) {
        (Some(up), Some(layer)) => {
            let (plan, plan_by_alternative) = match up.plan {
                Some(Plan::Unverified) => (layer.plan, layer.plan_by_alternative),
                _ => (up.plan, up.plan_by_alternative),
            };
            ExplainConfigOptionOutput {
                description: up.description.or(layer.description),
                types: up.types.or(layer.types),
                allowed_values: up.allowed_values.or(layer.allowed_values),
                default: up.default.or(layer.default),
                plan,
                plan_by_alternative,
                ..up
            }
        }
        (Some(up), None) => up,
        (None, Some(layer)) if in_config_patch => layer,
        (None, _) => return None,
    };

    Some(ExplainConfigOptionOutput {
        mirrord_json_path,
        ..output
    })
}

/// The entry of [`LAYER_CONFIG_PATHS`] a `mirrord-up.yaml` path falls under: the `mirrord.json`
/// path it maps onto, and the rest of the up path below it.
fn layer_config_mapping<'a, 'p>(segments: &'a [&'p str]) -> Option<(&'static str, &'a [&'p str])> {
    LAYER_CONFIG_PATHS.iter().find_map(|(up_path, layer_path)| {
        let up_segments: Vec<&str> = up_path.split('.').collect();
        let matches = segments.len() >= up_segments.len()
            && up_segments
                .iter()
                .zip(segments)
                .all(|(expected, segment)| *expected == "*" || expected == segment);
        matches.then(|| {
            (
                *layer_path,
                segments.get(up_segments.len()..).unwrap_or_default(),
            )
        })
    })
}

/// The `mirrord.json` path a `mirrord-up.yaml` path maps onto, per [`LAYER_CONFIG_PATHS`].
fn layer_config_path(segments: &[&str]) -> Option<String> {
    let (layer_path, rest) = layer_config_mapping(segments)?;
    let path = layer_path
        .split('.')
        .chain(rest.iter().copied())
        .filter(|segment| segment.is_empty().not())
        .collect::<Vec<_>>()
        .join(".");
    path.is_empty().not().then_some(path)
}

/// Describes the option at `segments` in `root`, or `None` when there is no such option.
fn explain(root: &Value, segments: &[&str]) -> Option<ExplainConfigOptionOutput> {
    let mut option = vec![Node::root(root)];
    let mut nodes = expand(root, option.iter().copied()).nodes;

    for segment in segments {
        let children = children(root, &nodes);
        let mut matching: Vec<Node> = children
            .iter()
            .filter(|(key, _)| *key == Some(*segment))
            .map(|(_, child)| *child)
            .collect();
        if matching.is_empty() {
            matching = children
                .iter()
                .filter(|(key, _)| key.is_none())
                .map(|(_, child)| *child)
                .collect();
        }
        if matching.is_empty() {
            return None;
        }

        nodes = expand(root, matching.iter().copied()).nodes;
        option = matching;
    }

    let mut types = Vec::new();
    let mut allowed_values = Vec::new();
    // Types taken without enumerating the values, like the target paths next to `targetless`.
    let mut free_types = Vec::new();
    for Node { schema, .. } in &nodes {
        let node_types: Vec<JsonType> = match schema.get("type") {
            Some(Value::Array(names)) => names
                .iter()
                .filter_map(|name| JsonType::deserialize(name).ok())
                .collect(),
            name => name
                .and_then(|name| JsonType::deserialize(name).ok())
                .into_iter()
                .collect(),
        };
        let values: Vec<&Value> = schema
            .get("enum")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
            .chain(schema.get("const"))
            .collect();
        if is_alternative(schema) && values.is_empty() {
            free_types.extend(node_types.iter().copied());
        }

        // A `const` may come without a `type`, e.g. `target: none` in a `mirrord-up.yaml`.
        let value_types = values.iter().copied().filter_map(JsonType::of);
        for json_type in node_types.iter().copied().chain(value_types) {
            if types.contains(&json_type).not() {
                types.push(json_type);
            }
        }
        for value in values {
            if allowed_values.contains(value).not() {
                allowed_values.push(value.clone());
            }
        }
    }

    // Values of a type the option also takes freely are examples rather than the allowed values.
    allowed_values.retain(|value| {
        JsonType::of(value).is_none_or(|json_type| free_types.contains(&json_type).not())
    });

    let (plan, plan_by_alternative) = plans(&nodes);
    Some(ExplainConfigOptionOutput {
        found: true,
        description: option
            .iter()
            .find_map(|node| description(root, node.schema, &mut HashSet::new()))
            .map(str::to_owned),
        types: types.is_empty().not().then_some(types),
        allowed_values: allowed_values.is_empty().not().then_some(allowed_values),
        default: nodes
            .iter()
            .find_map(|node| {
                node.schema
                    .get("default")
                    .filter(|value| value.is_null().not())
            })
            .cloned(),
        plan: Some(plan),
        plan_by_alternative,
        ..Default::default()
    })
}

/// Whether `schema` is one of the forms an option takes, rather than a choice between forms.
fn is_alternative(schema: &Value) -> bool {
    ["$ref", "anyOf", "oneOf", "allOf"]
        .iter()
        .all(|keyword| schema.get(keyword).is_none())
}

/// The description of `schema`: its own, or else the one of the type it refers to, or else the one
/// description among its alternatives. Several alternatives each with their own description (like
/// the target kinds) describe the alternatives rather than the option, and descriptions marked
/// `<!--${internal}-->` are notes for mirrord developers.
fn description<'s>(
    root: &'s Value,
    schema: &'s Value,
    refs: &mut HashSet<&'s str>,
) -> Option<&'s str> {
    if let Some(own) = schema.get("description").and_then(Value::as_str)
        && own.starts_with("<!--${internal}-->").not()
    {
        return Some(own);
    }

    if let Some(reference) = schema.get("$ref").and_then(Value::as_str)
        && refs.insert(reference)
        && let Some(target) = reference
            .strip_prefix('#')
            .and_then(|pointer| root.pointer(pointer))
    {
        return description(root, target, refs);
    }

    let mut found: Vec<&str> = Vec::new();
    for keyword in ["anyOf", "oneOf", "allOf"] {
        for branch in schema
            .get(keyword)
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
        {
            if let Some(branch) = description(root, branch, refs)
                && found.contains(&branch).not()
            {
                found.push(branch);
            }
        }
    }
    match found.as_slice() {
        [only] => Some(only),
        _ => None,
    }
}

/// The plan of an option, from the alternatives it accepts (the expanded `nodes` that offer no
/// further alternatives): the cheapest plan any of them needs, and each alternative's plan when
/// they differ. An alternative without a plan makes the option's plan [`Plan::Unverified`].
fn plans(nodes: &[Node]) -> (Plan, Option<Vec<AlternativePlan>>) {
    let alternatives: Vec<Node> = nodes
        .iter()
        .filter(|node| is_alternative(node.schema))
        .copied()
        .collect();

    let plan = match alternatives.iter().map(|node| node.plan).min() {
        Some(Some(plan)) if alternatives.iter().all(|node| node.plan.is_some()) => plan,
        _ => Plan::Unverified,
    };

    let mut by_alternative: Vec<AlternativePlan> = Vec::new();
    for node in &alternatives {
        let (Some(alternative), Some(plan)) = (alternative_name(node.schema), node.plan) else {
            continue;
        };
        if by_alternative
            .iter()
            .any(|known| known.alternative == alternative)
            .not()
        {
            by_alternative.push(AlternativePlan { alternative, plan });
        }
    }
    let differ = by_alternative
        .iter()
        .any(|alternative| alternative.plan != plan);

    (plan, differ.then_some(by_alternative))
}

/// How an agent tells one alternative of an option apart: its value when it is a constant, or the
/// field it requires when that is a single one, as with the target kinds.
fn alternative_name(schema: &Value) -> Option<String> {
    let value = schema
        .get("const")
        .or_else(|| match schema.get("enum")?.as_array()?.as_slice() {
            [value] => Some(value),
            _ => None,
        });
    if let Some(value) = value {
        return Some(
            value
                .as_str()
                .map_or_else(|| value.to_string(), str::to_owned),
        );
    }

    match schema.get("required")?.as_array()?.as_slice() {
        [field] => field.as_str().map(str::to_owned),
        _ => None,
    }
}

/// A schema reached while resolving a path.
#[derive(Debug, Clone, Copy)]
struct Node<'s> {
    schema: &'s Value,
    /// The plan from the schema's own [`PLAN_ANNOTATION`], or else the one inherited from the
    /// schemas that led to it.
    plan: Option<Plan>,
}

impl<'s> Node<'s> {
    fn root(schema: &'s Value) -> Self {
        Self { schema, plan: None }.child(schema)
    }

    /// `schema`, reached from `self`.
    fn child(self, schema: &'s Value) -> Self {
        let plan = schema
            .get(PLAN_ANNOTATION)
            .and_then(|plan| Plan::deserialize(plan).ok())
            .or(self.plan);
        Self { schema, plan }
    }
}

/// The schemas some value may be checked against.
struct Expanded<'s> {
    /// The given schemas and every schema they refer to or offer as an alternative, outermost
    /// first, so the docs of an option come before those of its type.
    nodes: Vec<Node<'s>>,
    /// The `$ref`s that were followed, to stop at recursive types when walking the schema.
    refs: HashSet<&'s str>,
}

/// Follows `$ref`, `anyOf`, `oneOf` and `allOf` from `nodes`.
fn expand<'s>(root: &'s Value, nodes: impl IntoIterator<Item = Node<'s>>) -> Expanded<'s> {
    fn visit<'s>(root: &'s Value, node: Node<'s>, expanded: &mut Expanded<'s>) {
        expanded.nodes.push(node);

        if let Some(reference) = node.schema.get("$ref").and_then(Value::as_str)
            && expanded.refs.insert(reference)
            && let Some(target) = reference
                .strip_prefix('#')
                .and_then(|pointer| root.pointer(pointer))
        {
            visit(root, node.child(target), expanded);
        }

        for keyword in ["anyOf", "oneOf", "allOf"] {
            for branch in node
                .schema
                .get(keyword)
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
            {
                visit(root, node.child(branch), expanded);
            }
        }
    }

    let mut expanded = Expanded {
        nodes: Vec::new(),
        refs: HashSet::new(),
    };
    for node in nodes {
        visit(root, node, &mut expanded);
    }
    expanded
}

/// The options directly below `nodes`, keyed by name, or by `None` for the entries of a map. The
/// options of an array's items count as the array's own, so `ports` of a list of filters is
/// reached as `<list>.ports`.
fn children<'s>(root: &'s Value, nodes: &[Node<'s>]) -> Vec<(Option<&'s str>, Node<'s>)> {
    let mut found = Vec::new();
    for node in nodes {
        if let Some(properties) = node.schema.get("properties").and_then(Value::as_object) {
            found.extend(
                properties
                    .iter()
                    .map(|(name, schema)| (Some(name.as_str()), node.child(schema))),
            );
        }
        if let Some(entries) = node
            .schema
            .get("additionalProperties")
            .filter(|schema| schema.is_object())
        {
            found.push((None, node.child(entries)));
        }
        if let Some(items) = node.schema.get("items").filter(|schema| schema.is_object()) {
            found.extend(children(root, &expand(root, [node.child(items)]).nodes));
        }
    }
    found
}

/// Every option path in `root`, with [`ANY_KEY`] for map keys. A recursive type is listed once,
/// not followed into itself.
fn known_paths(root: &Value) -> Vec<String> {
    fn walk<'s>(
        root: &'s Value,
        nodes: &[Node<'s>],
        prefix: &str,
        ancestors: &mut Vec<&'s str>,
        paths: &mut Vec<String>,
    ) {
        let children = children(root, nodes);
        let mut names: Vec<Option<&str>> = Vec::new();
        for (name, _) in &children {
            if names.contains(name).not() {
                names.push(*name);
            }
        }

        for name in names {
            let path = match prefix {
                "" => name.unwrap_or(ANY_KEY).to_owned(),
                _ => format!("{prefix}.{}", name.unwrap_or(ANY_KEY)),
            };
            let expanded = expand(
                root,
                children
                    .iter()
                    .filter(|(key, _)| *key == name)
                    .map(|(_, child)| *child),
            );
            paths.push(path.clone());

            if expanded
                .refs
                .iter()
                .any(|reference| ancestors.contains(reference))
            {
                continue;
            }
            let depth = ancestors.len();
            ancestors.extend(expanded.refs.iter().copied());
            walk(root, &expanded.nodes, &path, ancestors, paths);
            ancestors.truncate(depth);
        }
    }

    let mut paths = Vec::new();
    let root_nodes = expand(root, [Node::root(root)]);
    let mut ancestors = root_nodes.refs.into_iter().collect();
    walk(root, &root_nodes.nodes, "", &mut ancestors, &mut paths);
    paths
}

/// The [`SUGGESTIONS`] paths of `known` closest to the unknown path `segments`. Paths ending with
/// the asked one come first, so a path given without its parents (`incoming.mode`) still finds
/// the option; then the closest by edit distance.
///
/// Map keys in `known` take the asked path's own key at that position when the paths agree up to
/// there, so the suggestions for `services.api.htp_filter` are under `services.api`.
fn suggestions(segments: &[&str], known: &[String]) -> Vec<String> {
    let asked = segments.join(".");
    let mut ranked: Vec<(bool, f64, String)> = known
        .iter()
        .map(|path| {
            let mut candidate: Vec<&str> = Vec::new();
            for (index, segment) in path.split('.').enumerate() {
                let asked = segments.get(index).copied();
                let agrees = segments.get(..index) == Some(candidate.as_slice());
                candidate.push(match (segment, asked) {
                    (ANY_KEY, Some(asked)) if agrees => asked,
                    _ => segment,
                });
            }
            let candidate = candidate.join(".");
            let is_suffix = candidate.ends_with(&format!(".{asked}"));
            let similarity = strsim::normalized_damerau_levenshtein(&asked, &candidate);
            (is_suffix, similarity, candidate)
        })
        .collect();

    ranked.sort_by(|(suffix_a, similarity_a, _), (suffix_b, similarity_b, _)| {
        suffix_b
            .cmp(suffix_a)
            .then(similarity_b.total_cmp(similarity_a))
    });
    ranked
        .into_iter()
        .map(|(_, _, path)| path)
        .take(SUGGESTIONS)
        .collect()
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    fn explain_path(format: ConfigFormat, path: &str) -> ExplainConfigOptionOutput {
        explain_config_option(ExplainConfigOptionArgs {
            path: path.to_owned(),
            format: Some(format),
        })
        .unwrap()
    }

    #[test]
    fn enum_option() {
        let output = explain_path(ConfigFormat::MirrordJson, "feature.network.incoming.mode");
        assert!(output.found);
        assert!(output.description.is_some());
        assert_eq!(output.types, Some(vec![JsonType::String]));
        assert_eq!(
            output.allowed_values,
            Some(vec![json!("mirror"), json!("steal"), json!("off")])
        );
        assert_eq!(output.plan, Some(Plan::Oss));
        assert!(output.plan_by_alternative.is_none());
        assert!(output.suggestions.is_none());
    }

    /// Reached through a toggleable `http_filter`, which is a bool or a `$ref`'d object.
    #[test]
    fn nested_option() {
        let output = explain_path(
            ConfigFormat::MirrordJson,
            "feature.network.incoming.http_filter.header_filter",
        );
        assert!(output.found);
        assert!(output.description.unwrap().contains("header"));
        assert_eq!(output.types, Some(vec![JsonType::String]));
        assert!(output.allowed_values.is_none());
    }

    #[test]
    fn toggleable_option() {
        let output = explain_path(ConfigFormat::MirrordJson, "feature.network.incoming");
        let types = output.types.unwrap();
        assert!(types.contains(&JsonType::String), "{types:?}");
        assert!(types.contains(&JsonType::Object), "{types:?}");
    }

    #[test]
    fn default_value() {
        let output = explain_path(
            ConfigFormat::MirrordJson,
            "feature.network.incoming.tls_delivery.protocol",
        );
        assert_eq!(output.default, Some(json!("tls")));
    }

    #[test]
    fn map_entry() {
        let output = explain_path(ConfigFormat::MirrordJson, "feature.env.override.LOG_LEVEL");
        assert!(output.found);
        assert_eq!(output.types, Some(vec![JsonType::String]));
    }

    #[test]
    fn typo() {
        let output = explain_path(ConfigFormat::MirrordJson, "feature.network.incomng.mode");
        assert!(output.found.not());
        assert!(output.description.is_none());
        assert_eq!(
            output.suggestions.unwrap().first().map(String::as_str),
            Some("feature.network.incoming.mode")
        );
    }

    #[test]
    fn partial_path() {
        let output = explain_path(ConfigFormat::MirrordJson, "incoming.mode");
        assert!(output.found.not());
        assert_eq!(
            output.suggestions.unwrap().first().map(String::as_str),
            Some("feature.network.incoming.mode")
        );
    }

    #[test]
    fn empty_path() {
        let result = explain_config_option(ExplainConfigOptionArgs {
            path: " ".to_owned(),
            format: None,
        });
        assert!(matches!(result, Err(ExplainConfigOptionError::EmptyPath)));
    }

    #[test]
    fn up_option_mapped_onto_mirrord_json() {
        let output = explain_path(
            ConfigFormat::MirrordUpYaml,
            "services.api.http_filter.header_filter",
        );
        assert!(output.found);
        assert!(output.description.is_some());
        assert_eq!(
            output.mirrord_json_path.as_deref(),
            Some("feature.network.incoming.http_filter.header_filter")
        );
    }

    #[test]
    fn up_mode() {
        let output = explain_path(ConfigFormat::MirrordUpYaml, "services.api.default_mode");
        assert_eq!(
            output.allowed_values,
            Some(vec![json!("split"), json!("replace"), json!("mirror")])
        );
        assert_eq!(
            output.mirrord_json_path.as_deref(),
            Some("feature.network.incoming.mode")
        );
    }

    #[test]
    fn up_config_patch() {
        let output = explain_path(
            ConfigFormat::MirrordUpYaml,
            "services.api.config_patch.feature.fs.mode",
        );
        assert!(output.found);
        assert!(output.allowed_values.is_some());
        assert_eq!(output.mirrord_json_path.as_deref(), Some("feature.fs.mode"));
    }

    /// `none` is a bare `const`, without a `type`.
    #[test]
    fn up_target() {
        let output = explain_path(ConfigFormat::MirrordUpYaml, "services.api.target");
        let types = output.types.unwrap();
        assert!(types.contains(&JsonType::String), "{types:?}");
        assert!(types.contains(&JsonType::Object), "{types:?}");
        assert_eq!(output.allowed_values, Some(vec![json!("none")]));
    }

    /// `target`'s own description rather than that of one of its kinds, and no allowed values:
    /// `targetless` is one of many target strings.
    #[test]
    fn target() {
        let output = explain_path(ConfigFormat::MirrordJson, "target");
        let description = output.description.unwrap();
        assert!(
            description.starts_with("The Kubernetes workload"),
            "{description}"
        );
        assert!(output.allowed_values.is_none());
    }

    /// A `mirrord.json` option asked in a `mirrord-up.yaml` suggests the up setting that maps onto
    /// it, then setting it through `config_patch`. A map key is only filled in from the asked path
    /// where the paths agree up to it, so `feature.network.…` is not under a service called
    /// `network`.
    #[test]
    fn mirrord_json_path_in_up() {
        let output = explain_path(ConfigFormat::MirrordUpYaml, "feature.network.incoming.mode");
        assert!(output.found.not());
        let suggestions = output.suggestions.unwrap();
        assert_eq!(
            suggestions.get(..2),
            Some(
                [
                    "services.<name>.default_mode".to_owned(),
                    "services.<name>.config_patch.feature.network.incoming.mode".to_owned(),
                ]
                .as_slice()
            )
        );
        assert!(
            suggestions
                .iter()
                .all(|path| path.starts_with("services.<name>.")),
            "{suggestions:?}"
        );
    }

    /// A service's `target` holds a `path`, so `target.deployment` exists only in `mirrord.json`.
    #[test]
    fn up_path_only_in_mirrord_json() {
        let output = explain_path(
            ConfigFormat::MirrordUpYaml,
            "services.api.target.deployment",
        );
        assert!(output.found.not());
        let suggestions = output.suggestions.unwrap();
        assert!(
            suggestions.contains(&"services.api.target.path".to_owned()),
            "{suggestions:?}"
        );
    }

    #[test]
    fn up_only_option() {
        let output = explain_path(ConfigFormat::MirrordUpYaml, "services.api.run.command");
        assert!(output.found);
        assert!(output.description.is_some());
        assert!(output.mirrord_json_path.is_none());
    }

    #[test]
    fn up_typo() {
        let output = explain_path(ConfigFormat::MirrordUpYaml, "services.api.htp_filter");
        assert_eq!(
            output.suggestions.unwrap().first().map(String::as_str),
            Some("services.api.http_filter")
        );
    }

    #[test]
    fn plans() {
        for (format, path, plan) in [
            (ConfigFormat::MirrordJson, "feature.fs.mode", Plan::Oss),
            (
                ConfigFormat::MirrordJson,
                "feature.split_queues",
                Plan::Team,
            ),
            (
                ConfigFormat::MirrordJson,
                "feature.copy_target.scale_down",
                Plan::Team,
            ),
            (
                ConfigFormat::MirrordJson,
                "feature.network.incoming.tls_delivery.protocol",
                Plan::Team,
            ),
            (
                ConfigFormat::MirrordJson,
                "feature.preview",
                Plan::Enterprise,
            ),
            (
                ConfigFormat::MirrordJson,
                "target.path.deployment",
                Plan::Oss,
            ),
            (ConfigFormat::MirrordJson, "target.path.job", Plan::Team),
            (ConfigFormat::MirrordJson, "agent.ttl", Plan::Oss),
            (ConfigFormat::MirrordJson, "profile", Plan::Team),
            (ConfigFormat::MirrordJson, "multi_cluster", Plan::Enterprise),
            (
                ConfigFormat::MirrordUpYaml,
                "services.api.config_patch.feature.db_branches",
                Plan::Team,
            ),
            (
                ConfigFormat::MirrordUpYaml,
                "services.api.target.path.stateful_set",
                Plan::Team,
            ),
        ] {
            assert_eq!(explain_path(format, path).plan, Some(plan), "{path}");
        }
    }

    /// `target.path` can be used for free, but some kinds of targets need a paid plan.
    #[test]
    fn target_kinds() {
        let output = explain_path(ConfigFormat::MirrordJson, "target.path");
        assert_eq!(output.plan, Some(Plan::Oss));

        let by_alternative = output.plan_by_alternative.unwrap();
        for (alternative, plan) in [
            ("deployment", Plan::Oss),
            ("pod", Plan::Oss),
            ("rollout", Plan::Oss),
            ("job", Plan::Team),
            ("labels", Plan::Team),
            ("serverless", Plan::Enterprise),
        ] {
            assert!(
                by_alternative.contains(&AlternativePlan {
                    alternative: alternative.to_owned(),
                    plan,
                }),
                "{alternative}: {by_alternative:?}"
            );
        }
    }

    #[test]
    fn up_mode_plans() {
        let output = explain_path(ConfigFormat::MirrordUpYaml, "services.api.default_mode");
        assert_eq!(output.plan, Some(Plan::Oss));
        assert_eq!(
            output.plan_by_alternative,
            Some(vec![
                AlternativePlan {
                    alternative: "split".to_owned(),
                    plan: Plan::Oss,
                },
                AlternativePlan {
                    alternative: "replace".to_owned(),
                    plan: Plan::Team,
                },
                AlternativePlan {
                    alternative: "mirror".to_owned(),
                    plan: Plan::Oss,
                },
            ])
        );
    }

    #[test]
    fn plan_inheritance() {
        let schema = json!({
            "properties": {
                "copy_target": {
                    "x-mirrord-plan": "team",
                    "anyOf": [{ "$ref": "#/$defs/CopyTarget" }, { "type": "null" }],
                },
                "fs": { "type": "string" },
            },
            "$defs": {
                "CopyTarget": {
                    "type": "object",
                    "properties": {
                        "scale_down": { "type": "boolean" },
                        "preview": { "x-mirrord-plan": "enterprise", "type": "boolean" },
                    },
                },
            },
        });

        let plan = |path: &str| {
            let segments: Vec<&str> = path.split('.').collect();
            explain(&schema, &segments).unwrap().plan
        };
        assert_eq!(plan("copy_target"), Some(Plan::Team));
        assert_eq!(plan("copy_target.scale_down"), Some(Plan::Team));
        assert_eq!(plan("copy_target.preview"), Some(Plan::Enterprise));
        assert_eq!(plan("fs"), Some(Plan::Unverified));
    }

    /// Every option needs a plan, its own or its parent's: `#[config(plan = "...")]` on fields
    /// generated by `MirrordConfig`, `#[schemars(extend("x-mirrord-plan" = "..."))]` elsewhere.
    #[test]
    fn every_option_has_a_plan() {
        let missing: Vec<&String> = LAYER_PATHS
            .iter()
            .filter(|path| {
                explain_path(ConfigFormat::MirrordJson, path).plan == Some(Plan::Unverified)
            })
            .collect();
        assert!(missing.is_empty(), "options without a plan: {missing:#?}");
    }

    /// Every option under `feature` needs a plan of its own rather than inheriting `feature`'s, so
    /// a new feature can't be added without deciding which plan it needs.
    #[test]
    fn every_feature_has_its_own_plan() {
        let features = LAYER_SCHEMA
            .raw
            .pointer("/$defs/FeatureFileConfig/properties")
            .and_then(Value::as_object)
            .unwrap();
        let missing: Vec<&String> = features
            .iter()
            .filter(|(_, schema)| {
                schema
                    .get(PLAN_ANNOTATION)
                    .and_then(|plan| Plan::deserialize(plan).ok())
                    .is_none()
            })
            .map(|(name, _)| name)
            .collect();
        assert!(missing.is_empty(), "features without a plan: {missing:#?}");
    }

    /// Every target kind needs a plan of its own, rather than inheriting `target`'s.
    #[test]
    fn every_target_kind_has_a_plan() {
        let kinds = LAYER_SCHEMA
            .raw
            .pointer("/$defs/Target/oneOf")
            .and_then(Value::as_array)
            .unwrap();
        for kind in kinds {
            let kind = match kind.get("$ref").and_then(Value::as_str) {
                Some(reference) => LAYER_SCHEMA.raw.pointer(&reference[1..]).unwrap(),
                None => kind,
            };
            let plan = kind.get(PLAN_ANNOTATION).cloned();
            assert!(
                plan.and_then(|plan| Plan::deserialize(plan).ok()).is_some(),
                "target kind without a valid plan: {kind}"
            );
        }
    }

    #[test]
    fn every_up_option_has_a_plan() {
        let missing: Vec<&String> = UP_PATHS
            .iter()
            .filter(|path| {
                explain_path(ConfigFormat::MirrordUpYaml, path).plan == Some(Plan::Unverified)
            })
            .collect();
        assert!(missing.is_empty(), "options without a plan: {missing:#?}");
    }

    #[test]
    fn layer_config_paths_resolve() {
        for (up_path, layer_path) in LAYER_CONFIG_PATHS {
            let up_segments: Vec<&str> = up_path.split('.').collect();
            assert!(explain(&UP_SCHEMA.raw, &up_segments).is_some(), "{up_path}");
            if layer_path.is_empty().not() {
                let layer_segments: Vec<&str> = layer_path.split('.').collect();
                assert!(
                    explain(&LAYER_SCHEMA.raw, &layer_segments).is_some(),
                    "{layer_path}"
                );
            }
        }
    }
}
