name: Build Agent Image
description: Build the mirrord agent Docker image and upload as artifact

runs:
  using: composite
  steps:
    - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd
    - name: build and export
      uses: docker/bake-action@82490499d2e5613fcead7e128237ef0b0ea210f7
      env:
        DOCKER_BUILD_RECORD_UPLOAD: "false"
        PLATFORMS: "linux/amd64"
        AGENT_TAGS: "test"
      with:
        source: .
        files: ci/docker-bake.hcl
        targets: agent
        set: |
          agent.output=type=docker,dest=${{ github.workspace }}/test.tar
    - name: upload image
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
      with:
        name: test
        path: ${{ github.workspace }}/test.tar
