name: Build Agent Image
description: Build the mirrord agent Docker image and upload as artifact

runs:
  using: composite
  steps:
    - uses: docker/setup-buildx-action@v3
    - name: build and export
      shell: bash
      env:
        PLATFORMS: "linux/amd64"
        AGENT_TAGS: "test"
      run: docker buildx bake -f ci/docker-bake.hcl agent --set "agent.output=type=docker,dest=${{ github.workspace }}/test.tar"
    - name: upload image
      uses: actions/upload-artifact@v4
      with:
        name: test
        path: ${{ github.workspace }}/test.tar
