use std::collections::HashMap;

use mirrord_analytics::{AnalyticValue, CollectAnalytics};
use mirrord_config_derive::MirrordConfig;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use super::{FsModeConfig, FsUserConfig};
use crate::{
    config::{ConfigContext, ConfigError, from_env::FromEnv, source::MirrordConfigSource},
    util::{MirrordToggleableConfig, VecOrSingle},
};

/// The default size in bytes used for buffering read-only remote files.
/// See [`FsConfig::readonly_file_buffer`].
pub const READONLY_FILE_BUFFER_DEFAULT: u64 = 128000;
/// Warn users if using a value of [`FsConfig::readonly_file_buffer`] larger than 1mb
pub const READONLY_FILE_BUFFER_WARN_LIMIT: u64 = 1024 * 1024;
/// Do not allow users to set a value of [`FsConfig::readonly_file_buffer`] larger than 15mb
pub const READONLY_FILE_BUFFER_HARD_LIMIT: u64 = 15 * 1024 * 1024;

/// The default number of seconds allowed for each agent request made while prefetching.
/// See [`FsConfig::prefetch_timeout`].
pub const PREFETCH_TIMEOUT_DEFAULT: u64 = 30;

// TODO(alex): We could turn this derive macro (`MirrordConfig`) into an attribute version, which
// would allow us to "capture" the `derive` statement, making it possible to implement the same for
// whatever is generated by `map_to`.

/// Allows the user to specify the default behavior for file operations:
///
/// 1. `"read"` or `true` - Read from the remote file system (default)
/// 2. `"write"` - Read/Write from the remote file system.
/// 3. `"local"` or `false` - Read from the local file system.
/// 4. `"localwithoverrides"` - perform fs operation locally, unless the path matches a pre-defined
///    or user-specified exception.
///
/// > Note: by default, some paths are read locally or remotely, regardless of the selected FS mode.
/// > This is described in further detail below.
///
/// Besides the default behavior, the user can specify behavior for specific regex patterns.
/// Case insensitive.
///
/// 1. `"read_write"` - List of patterns that should be read/write remotely.
/// 2. `"read_only"` - List of patterns that should be read only remotely.
/// 3. `"local"` - List of patterns that should be read locally.
/// 4. `"not_found"` - List of patterns that should never be read nor written. These files should be
///    treated as non-existent.
/// 4. `"mapping"` - Map of patterns and their corresponding replacers. The replacement happens before any specific behavior as defined above or mode (uses [`Regex::replace`](https://docs.rs/regex/latest/regex/struct.Regex.html#method.replace))
///
/// The logic for choosing the behavior is as follows:
///
///
/// 1. Check against "mapping" if path needs to be replaced, if matched then continue to next step
///    with new path after replacements otherwise continue as usual.
/// 2. Check if one of the patterns match the file path, do the corresponding action. There's no
///    specified order if two lists match the same path, we will use the first one (and we do not
///    guarantee what is first).
///
///    **Warning**: Specifying the same path in two lists is unsupported and can lead to undefined
///    behaviour.
///
/// 3. There are pre-defined exceptions to the set FS mode.
///   1. Paths that match the pre-defined patterns [for Linux/MacOS](https://github.com/metalbear-co/mirrord/tree/latest/mirrord/layer-lib/src/file/unix/read_local_by_default.rs)
///      or [for Windows](https://github.com/metalbear-co/mirrord/tree/latest/mirrord/layer-lib/src/file/windows/read_local_by_default.rs)
///      are read locally by default.
///   2. Paths that match the pre-defined patterns [for Linux/MacOS](https://github.com/metalbear-co/mirrord/tree/latest/mirrord/layer-lib/src/file/unix/read_remote_by_default.rs)
///      or [for Windows](https://github.com/metalbear-co/mirrord/tree/latest/mirrord/layer-lib/src/file/windows/read_remote_by_default.rs)
///      are read remotely by default when the mode is `localwithoverrides`.
///   3. Paths that match the pre-defined patterns [for Linux/MacOS](https://github.com/metalbear-co/mirrord/tree/latest/mirrord/layer-lib/src/file/unix/not_found_by_default.rs)
///      or [for Windows](https://github.com/metalbear-co/mirrord/tree/latest/mirrord/layer-lib/src/file/windows/not_found_by_default.rs)
///      under the running user's home directory will not be found by the application when the mode
///      is not `local`.
///
///   In order to override that default setting for a path, or a pattern, include it the
///   appropriate pattern set from above. E.g. in order to read files under `/etc/` remotely even
///   though it is covered by the set of pre-defined patterns that are read locally by default,
///   add `"^/etc/."` to the `read_only` set.
///
/// 4. If none of the above match, use the default behavior (mode).
///
/// For more information, check the file operations
/// [technical reference](https://metalbear.com/mirrord/docs/reference/fileops/).
///
/// ```json
/// {
///   "feature": {
///     "fs": {
///       "mode": "write",
///       "read_write": ".+\\.json" ,
///       "read_only": [ ".+\\.yaml", ".+important-file\\.txt" ],
///       "local": [ ".+\\.js", ".+\\.mjs" ],
///       "not_found": [ "\\.config/gcloud" ],
///       "prefetch": [ "/etc/ssl" ]
///     }
///   }
/// }
/// ```
///
/// #### Windows paths {#fs-windows-paths}
///
/// On Windows, the patterns of `read_write`, `read_only`, `local`, `not_found` and `mapping` are
/// matched against two forms of the path, both with forward slashes:
///
/// | Form | `D:\Workspaces\myapp\app.json` becomes | A pattern for this form matches |
/// |---|---|---|
/// | without the drive | `/Workspaces/myapp/app.json` | the path on every drive |
/// | with the drive | `D:/Workspaces/myapp/app.json` | the path on that drive only |
///
/// A pattern applies when it matches either form. So `^/Workspaces/` matches the folder on
/// every drive, and `^D:/Workspaces/` matches it on `D:` only. Like the rest of a pattern, the
/// drive letter ignores case.
///
/// Write patterns with forward slashes. A backslash in a pattern never matches, since neither
/// form has one, and mirrord warns about a pattern that looks like a path with backslashes.
///
/// For a path from the environment, use the `path_pattern` template filter. It gives the path's
/// form with the drive, escaped so that it matches literally and fits in any config format.
///
/// `%TEMP%` is read locally by default. To use the pod's `/tmp` instead, map it:
///
/// ```json
/// {
///   "feature": {
///     "fs": {
///       "mapping": {
///         "^{{ get_env(name='TEMP') | path_pattern }}/(.*)$": "/tmp/$1"
///       }
///     }
///   }
/// }
/// ```
///
/// - **Both the short and long name of a folder match.** Windows can give a folder an old-style
///   short name, like `FIRSTN~1` for `First Name`, and `%TEMP%` often uses it. `path_pattern`
///   matches both, as long as the folder exists.
/// - **The result never ends in a separator.** Add `/` to match what's inside the folder.
/// - **For text that isn't a path,** such as a user name, `regex_escape` escapes it as-is.
#[derive(MirrordConfig, Default, Clone, PartialEq, Eq, Debug, Serialize, Deserialize)]
#[config(
    map_to = "AdvancedFsUserConfig",
    derive = "PartialEq, Eq, JsonSchema, Serialize",
    generator = "FsUserConfig"
)]
pub struct FsConfig {
    /// #### feature.fs.mode {#feature-fs-mode}
    #[config(nested)]
    pub mode: FsModeConfig,

    /// #### feature.fs.read_write {#feature-fs-read_write}
    ///
    /// Specify file path patterns that if matched will be read and written to the remote.
    ///
    /// On Windows, write the patterns with forward slashes. They match the path with and without
    /// its drive, as [Windows paths](#fs-windows-paths) explains.
    #[config(env = "MIRRORD_FILE_READ_WRITE_PATTERN")]
    pub read_write: Option<VecOrSingle<String>>,

    /// #### feature.fs.read_only {#feature-fs-read_only}
    ///
    /// Specify file path patterns that if matched will be read from the remote.
    /// if file matching the pattern is opened for writing or read/write it will be opened locally.
    ///
    /// On Windows, write the patterns with forward slashes. They match the path with and without
    /// its drive, as [Windows paths](#fs-windows-paths) explains.
    pub read_only: Option<VecOrSingle<String>>,

    /// #### feature.fs.local {#feature-fs-local}
    ///
    /// Specify file path patterns that if matched will be opened locally.
    ///
    /// On Windows, write the patterns with forward slashes. They match the path with and without
    /// its drive, as [Windows paths](#fs-windows-paths) explains.
    #[config(env = "MIRRORD_FILE_LOCAL_PATTERN")]
    pub local: Option<VecOrSingle<String>>,

    /// #### feature.fs.not_found {#feature-fs-not_found}
    ///
    /// Specify file path patterns that if matched will be treated as non-existent.
    ///
    /// On Windows, write the patterns with forward slashes. They match the path with and without
    /// its drive, as [Windows paths](#fs-windows-paths) explains.
    pub not_found: Option<VecOrSingle<String>>,

    /// #### feature.fs.mapping {#feature-fs-mapping}
    ///
    /// Specify map of patterns that if matched will replace the path according to specification.
    ///
    /// *Capture groups are allowed.* Matching is case-insensitive and uses
    /// [`Regex::replace`](https://docs.rs/regex/latest/regex/struct.Regex.html#method.replace),
    /// so the replacement value supports `$1` / `${name}` substitutions.
    ///
    /// ##### Unix (Linux, macOS)
    ///
    /// Patterns are matched against the path exactly as the application requested it.
    ///
    /// Example:
    /// ```json
    /// {
    ///   "^/home/(?<user>\\S+)/dev/tomcat": "/etc/tomcat",
    ///   "^/home/(?<user>\\S+)/dev/config/(?<app>\\S+)": "/mnt/configs/${user}-$app"
    /// }
    /// ```
    ///
    /// Will produce the following replacements for any io operation:
    ///
    /// `/home/johndoe/dev/tomcat/context.xml` => `/etc/tomcat/context.xml`
    /// `/home/johndoe/dev/config/api/app.conf` => `/mnt/configs/johndoe-api/app.conf`
    ///
    /// ##### Windows
    ///
    /// Patterns match the path with and without its drive, with forward slashes, as
    /// [Windows paths](#fs-windows-paths) explains:
    ///
    /// - **A pattern without a drive** (`^/Workspaces/`) maps the path on every drive.
    /// - **A pattern with a drive** (`^C:/Repos/`) maps the path on that drive only.
    ///
    /// The value is the path the remote (Linux) pod opens, so write it with forward slashes and
    /// no drive. A drive left in the result is dropped.
    ///
    /// Example:
    /// ```json
    /// {
    ///   "^/Workspaces/(?<app>[^/]+)/config/(?<file>.+)": "/etc/${app}/$file",
    ///   "^C:/Repos/api/appsettings\\.json$": "/app/appsettings.json"
    /// }
    /// ```
    ///
    /// Will produce the following replacements:
    ///
    /// `D:\Workspaces\myapp\config\app.json` => `/etc/myapp/app.json`
    /// `C:\Repos\api\appsettings.json` => `/app/appsettings.json`
    ///
    /// `D:\Repos\api\appsettings.json` stays as it is, because the second pattern names `C:`.
    ///
    /// ##### Caveats
    ///
    /// - Relative paths: this feature (currently) does not apply mappings to relative paths, e.g.
    ///   `../dev`.
    pub mapping: Option<HashMap<String, String>>,

    /// #### feature.fs.readonly_file_buffer {#feature-fs-readonly_file_buffer}
    ///
    /// Sets buffer size for read-only remote files in bytes. By default, the value is
    /// 128000 bytes, or 128 kB.
    ///
    /// Setting the value to 0 disables file buffering.
    /// Otherwise, read-only remote files will be read in chunks and buffered locally.
    /// This improves performance when the user application reads data in small portions.
    #[config(default = READONLY_FILE_BUFFER_DEFAULT)]
    pub readonly_file_buffer: u64,

    /// #### feature.fs.prefetch {#feature-fs-prefetch}
    ///
    /// Remote paths to download from the target before the local process starts.
    ///
    /// Each path is copied from the remote filesystem into a temporary local directory, along
    /// with its permissions. Operations on these paths are then served from that local copy,
    /// without involving the agent at all. Directories are copied recursively.
    ///
    /// Writes go to the copy as well, and are never sent to the target. The application reads
    /// back whatever it wrote for the rest of the run, and the copy is abandoned when the run
    /// ends, leaving the target untouched. A write reaches the copy only when the
    /// [`mode`](#feature-fs-mode) would otherwise have sent it to the target, that is under
    /// `write`; under the other modes writes stay on the local filesystem under their original
    /// path, as they do for every other file.
    ///
    /// The copy keeps the permissions it had in the target, so a file that is read-only there is
    /// read-only here, and writing to it fails locally much as it would remotely.
    ///
    /// **Do not prefetch secrets.** The copy is written to a temporary directory on the machine
    /// running mirrord, guarded by nothing more than that machine's own permissions, rather than
    /// by the cluster. It is deleted when the session ends, but a session that is killed outright
    /// leaves it behind, since nothing gets to run.
    ///
    /// Creating, deleting and renaming still act on the target: a file created under a prefetched
    /// directory is not part of the copy, and deleting or renaming a prefetched path takes effect
    /// remotely rather than in the copy.
    ///
    /// This trades startup time for read throughput, and is meant for applications that
    /// repeatedly read a small and stable set of remote files, e.g. an HTTP server that reads
    /// `/etc/ssl` on every request.
    ///
    /// Because the copy is taken once, before the application starts, changes made to these
    /// paths in the pod afterwards are invisible to the application.
    ///
    /// Paths must start with `/`, as they are resolved in the remote pod, where the local
    /// process's working directory is meaningless.
    ///
    /// Not supported on Windows, where the option is ignored.
    ///
    /// ```json
    /// {
    ///   "feature": {
    ///     "fs": {
    ///       "mode": "read",
    ///       "prefetch": [ "/etc/ssl", "/app/config.yaml" ]
    ///     }
    ///   }
    /// }
    /// ```
    pub prefetch: Option<Vec<String>>,

    /// #### feature.fs.prefetch_timeout {#feature-fs-prefetch_timeout}
    ///
    /// How long to wait, in seconds, for each request to the agent made while copying
    /// [`prefetch`](#feature-fs-prefetch) paths. By default, the value is 30 seconds.
    ///
    /// The limit is per request rather than for the whole copy, which makes many requests: one
    /// per directory listing, and one per chunk of every file. Raise it when copying from a slow
    /// or distant cluster, where a single request can outlast the default.
    ///
    /// A path that runs out of time is skipped with a warning, and is read from the remote as
    /// usual.
    #[config(default = PREFETCH_TIMEOUT_DEFAULT)]
    pub prefetch_timeout: u64,
}

impl MirrordToggleableConfig for AdvancedFsUserConfig {
    fn disabled_config(context: &mut ConfigContext) -> Result<Self::Generated, ConfigError> {
        let mode = FsModeConfig::disabled_config(context)?;
        let read_write = FromEnv::new("MIRRORD_FILE_READ_WRITE_PATTERN")
            .source_value(context)
            .transpose()?;
        let read_only = FromEnv::new("MIRRORD_FILE_READ_ONLY_PATTERN")
            .source_value(context)
            .transpose()?;
        let local = FromEnv::new("MIRRORD_FILE_LOCAL_PATTERN")
            .source_value(context)
            .transpose()?;

        Ok(Self::Generated {
            mode,
            read_write,
            read_only,
            local,
            not_found: None,
            mapping: None,
            readonly_file_buffer: READONLY_FILE_BUFFER_DEFAULT,
            prefetch: None,
            prefetch_timeout: PREFETCH_TIMEOUT_DEFAULT,
        })
    }
}

impl FsConfig {
    pub fn is_read(&self) -> bool {
        self.mode.is_read()
    }

    pub fn is_write(&self) -> bool {
        self.mode.is_write()
    }

    /// Checks if fs operations are active
    pub fn is_active(&self) -> bool {
        !matches!(self.mode, FsModeConfig::Local)
    }

    /// Warns about each pattern written as a Windows path with backslashes.
    ///
    /// On Windows, the layer matches paths with forward slashes only, so such a pattern matches
    /// nothing, and often isn't a valid regex either (`\R` in `C:\Repos`). It's a warning rather
    /// than an error, and Windows only, because elsewhere a backslash is an ordinary file name
    /// character.
    pub fn verify(&self, context: &mut ConfigContext) {
        if !cfg!(windows) {
            return;
        }

        for (list, pattern) in self.backslash_path_patterns() {
            context.add_warning(format!(
                "`feature.fs.{list}` pattern `{pattern}` is a path with backslashes, but on \
                 Windows mirrord matches paths with forward slashes: `C:\\Repos\\app.json` is \
                 matched as `C:/Repos/app.json` and `/Repos/app.json`, so this pattern never \
                 matches. Write it with `/`, and for a path from the environment use a template: \
                 `{{{{ get_env(name='TEMP') | path_pattern }}}}`."
            ));
        }
    }

    /// The patterns, with the list each is in, that look like a Windows path written with
    /// backslashes: they start with a drive and a backslash (`C:\Repos`), or match a backslash
    /// (`\\`), which no path the layer matches holds.
    fn backslash_path_patterns(&self) -> impl Iterator<Item = (&'static str, &str)> {
        let lists = [
            ("read_write", &self.read_write),
            ("read_only", &self.read_only),
            ("local", &self.local),
            ("not_found", &self.not_found),
        ]
        .into_iter()
        .flat_map(|(list, patterns)| {
            patterns
                .as_deref()
                .unwrap_or_default()
                .iter()
                .map(move |pattern| (list, pattern.as_str()))
        });
        let mapping = self
            .mapping
            .iter()
            .flatten()
            .map(|(pattern, _)| ("mapping", pattern.as_str()));

        lists.chain(mapping).filter(|(_, pattern)| {
            let unanchored = pattern.strip_prefix('^').unwrap_or(pattern);
            let starts_with_drive = matches!(
                unanchored.as_bytes(),
                [letter, b':', b'\\', ..] if letter.is_ascii_alphabetic()
            );
            starts_with_drive || pattern.contains(r"\\")
        })
    }
}

impl From<FsModeConfig> for AnalyticValue {
    fn from(mode: FsModeConfig) -> Self {
        match mode {
            FsModeConfig::Local => Self::Number(0),
            FsModeConfig::LocalWithOverrides => Self::Number(1),
            FsModeConfig::Read => Self::Number(2),
            FsModeConfig::Write => Self::Number(3),
        }
    }
}

impl CollectAnalytics for &FsConfig {
    fn collect_analytics(&self, analytics: &mut mirrord_analytics::Analytics) {
        analytics.add("mode", self.mode);
        analytics.add(
            "local_paths",
            self.local.as_deref().map(<[_]>::len).unwrap_or_default(),
        );
        analytics.add(
            "read_write_paths",
            self.read_write
                .as_deref()
                .map(<[_]>::len)
                .unwrap_or_default(),
        );
        analytics.add(
            "read_only_paths",
            self.read_only
                .as_deref()
                .map(<[_]>::len)
                .unwrap_or_default(),
        );
        analytics.add(
            "not_found_paths",
            self.not_found
                .as_deref()
                .map(<[_]>::len)
                .unwrap_or_default(),
        );
        analytics.add("readonly_file_buffer", self.readonly_file_buffer);
        analytics.add(
            "prefetch_paths",
            self.prefetch.as_deref().map(<[_]>::len).unwrap_or_default(),
        );
        analytics.add("prefetch_timeout", self.prefetch_timeout);
    }
}

#[cfg(test)]
mod tests {
    use rstest::rstest;

    use super::*;
    use crate::config::MirrordConfig;

    #[rstest]
    fn advanced_fs_config_default() {
        let expect = FsConfig {
            mode: FsModeConfig::Read,
            readonly_file_buffer: READONLY_FILE_BUFFER_DEFAULT,
            prefetch_timeout: PREFETCH_TIMEOUT_DEFAULT,
            ..Default::default()
        };

        let mut cfg_context = ConfigContext::default().strict_env(true);

        let fs_config = AdvancedFsUserConfig::default()
            .generate_config(&mut cfg_context)
            .unwrap();

        assert_eq!(fs_config, expect);
    }

    /// The warnings [`FsConfig::verify`] gives for `config`.
    #[cfg(windows)]
    fn warnings(config: FsConfig) -> Vec<String> {
        let mut context = ConfigContext::default();
        config.verify(&mut context);
        context.into_warnings()
    }

    /// The patterns customers write when they copy a path from Explorer: backslashes, escaped
    /// once for JSON (`C:\Repos`) or twice more for the regex (`C:\\Repos`).
    #[cfg(windows)]
    #[rstest]
    #[case::escaped_for_json(r"C:\Repos\app\appsettings.json")]
    #[case::escaped_for_the_regex(r"C:\\Repos\\app\\appsettings\.json")]
    #[case::anchored(r"^C:\Repos\app")]
    #[case::without_a_drive(r"\\Repos\\app")]
    fn a_path_with_backslashes_is_warned_about_in_every_list(#[case] pattern: &str) {
        let patterns = || Some(VecOrSingle::Single(pattern.to_owned()));
        let lists = [
            (
                "read_write",
                FsConfig {
                    read_write: patterns(),
                    ..Default::default()
                },
            ),
            (
                "read_only",
                FsConfig {
                    read_only: patterns(),
                    ..Default::default()
                },
            ),
            (
                "local",
                FsConfig {
                    local: patterns(),
                    ..Default::default()
                },
            ),
            (
                "not_found",
                FsConfig {
                    not_found: patterns(),
                    ..Default::default()
                },
            ),
            (
                "mapping",
                FsConfig {
                    mapping: Some([(pattern.to_owned(), "/app".to_owned())].into()),
                    ..Default::default()
                },
            ),
        ];

        for (list, config) in lists {
            let warnings = warnings(config);
            let [warning] = warnings.as_slice() else {
                panic!("one warning for `{list}`, got {warnings:?}");
            };
            assert!(
                warning.contains(&format!("`feature.fs.{list}` pattern `{pattern}`")),
                "the warning names the list and the pattern: {warning}"
            );
        }
    }

    /// Ordinary regexes use backslashes too, to escape a `.` or for a class like `\d`: those are
    /// not paths, and get no warning.
    #[cfg(windows)]
    #[rstest]
    #[case::forward_slashes("^C:/Repos/app/")]
    #[case::escaped_dot(r".+\.json$")]
    #[case::digit_class(r"^/logs/\d+\.log$")]
    fn a_regex_escape_is_not_warned_about(#[case] pattern: &str) {
        let config = FsConfig {
            read_only: Some(VecOrSingle::Single(pattern.to_owned())),
            ..Default::default()
        };

        assert_eq!(warnings(config), Vec::<String>::new());
    }
}
