StylesPath = .vale/styles
MinAlertLevel = suggestion
Packages = write-good, Google
IgnoredScopes = code, tt, strong, summary
Vocab = Metalbear

[formats]
rs = md

[*.md]
BasedOnStyles = Vale, write-good, Google, Metalbear
# ignore markdown links and emails
TokenIgnores = (\[[^\]]*\]\(.*?\)), (\S+@\S+\.\S+)

[*.rs]
BasedOnStyles = Vale, Google, Metalbear
View = RustComments
Vale.Spelling = NO
