[build.env]
passthrough = [
    "MIRRORD_LAYER_FILE",
    "MIRRORD_LAYER_IMAGE_TAG",
]
volumes = ["WIZARD_DIST_DIR"]
# Dockerfile used for building mirrord-layer for x64 with very old libc
# this to support centos7 or Amazon Linux 2.
[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/metalbear-co/ci-layer-build:${MIRRORD_LAYER_IMAGE_TAG:-latest}"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/metalbear-co/ci-layer-build-aarch64:${MIRRORD_LAYER_IMAGE_TAG:-latest}"