[package]
name = "mirrord-tls-util"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true
edition.workspace = true

[features]

[dependencies]
http.workspace = true
rcgen.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "net"] }
tokio-rustls.workspace = true
tracing.workspace = true
x509-parser.workspace = true

[dev-dependencies]
pem.workspace = true
tempfile.workspace = true
