name: 🐛 Bug Report
description: Create a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
        Please fill out the form below...

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please provide a clear description of the bug.
      placeholder: The bug is...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Provide steps to reproduce this bug.
        If this bug is related to you application not functioning correctly with mirrord,
        we would appreciate providing a link to a repository with a minimal reproducible example.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: debug
    attributes:
      label: Backtrace
      description: If your bug produces a backtrace, please include it here.
      render: shell

  - type: textarea
    id: layer-logs
    attributes:
      label: mirrord layer logs
      description: |
        If possible, reproduce the bug and attach the relevant `mirrord-layer` logs.
        You can enable them by setting the `RUST_LOG` environment variable to `mirrord=trace`.
        You will find them in your application's STDERR.
      render: shell

  - type: textarea
    id: intproxy-logs
    attributes:
      label: mirrord intproxy logs
      description: |
        If possible, reproduce the bug and attach the relevant `mirrord-intproxy` logs.
        You can enable them by setting [`internal_proxy.log_level`](https://metalbear.co/mirrord/docs/reference/configuration/#internal_proxy-log_level) to `mirrord=trace` in your mirrord config.
        By default, `mirrord-intproxy` logs are dumped to a file in the `/tmp` directory (complete path looks like `/tmp/mirrord-intproxy-1727386366-5rqqf2x.log`).
        You can override logs destination in the `internal_proxy.log_destination` mirrord config entry.
      render: shell

  - type: textarea
    id: agent-logs
    attributes:
      label: mirrord agent logs
      description: |
        If possible, reproduce the bug and attach the relevant `mirrord-agent` logs.
        You can enable them by setting `agent.log_level` to `mirrord=trace` in your mirrord config.
        You can fetch them from agent's pod (or ephemeral container, depending on your agent config).
      render: shell

  - type: textarea
    id: mirrord-config
    attributes:
      label: mirrord config
      description: If you were using a custom mirrord config, please attach it here.
      render: json

  - type: input
    id: cli-version
    attributes:
      label: mirrord CLI version

  - type: input
    id: agent-version
    attributes:
      label: mirrord-agent version

  - type: input
    id: operator-version
    attributes:
      label: mirrord-operator version (if relevant)
      description: You can check it using `mirrord operator status` command.

  - type: input
    id: plugin-name
    attributes:
      label: plugin kind and version (if relevant)
      description: For example "IntelliJ, 3.63.0" or "VSCode, 3.60.0".

  - type: input
    id: os_version
    attributes:
      label: Your operating system and version
    validations:
      required: true

  - type: input
    id: binary_type
    attributes:
      label: Local process
      description: What process are you trying to run with mirrord? Please run `file $(which <process name>)` for best results.
    validations:
      required: true

  - type: input
    id: binary_version
    attributes:
      label: Local process version
      description: What's the version of the process you're trying to run with mirrord?

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Any additional info that you think might be useful or relevant to this bug
