name: 🐛 Bug Report
description: Create a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
        Please fill out the form below...
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please provide a clear description of the bug.
      placeholder: The bug is...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce this bug.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: debug
    attributes:
      label: Backtrace
      description: If your bug produces a backtrace, please include it here.
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: If possible, reproduce the bug with the envrionment variable RUST_LOG set to 'trace', and attach the printed logs
      render: shell
  - type: input
    id: os_version
    attributes:
      label: Your operating system and version
    validations:
      required: true
  - type: input
    id: binary_type
    attributes:
      label: Local process
      description: What process are you trying to run with mirrord? Please run `file $(which <process name>)` for best results.
    validations:
      required: true
  - type: input
    id: binary_version
    attributes:
      label: Local process version
      description: What's the version of the process you're trying to run with mirrord?
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Any additional info that you think might be useful or relevant to this bug
