use std::{
    collections::{BTreeSet, HashMap},
    ops::Not,
};

use clap::{ValueEnum, builder::PossibleValue};
use mirrord_analytics::{Analytics, CollectAnalytics};
use mirrord_config::{
    LayerConfig, LayerFileConfig,
    config::{ConfigContext, EnvKey, MirrordConfig},
    feature::{
        env::EnvConfig,
        network::incoming::{IncomingMode, http_filter::HttpFilterConfig},
        split_queues::SplitQueuesConfig,
    },
    target::Target,
};
use serde::{Deserialize, Serialize};
use strum::VariantArray;
use strum_macros::{Display, IntoStaticStr, VariantArray};

/// Incoming traffic mode for a service.
#[derive(
    Clone, Debug, Default, Serialize, Deserialize, PartialEq, VariantArray, IntoStaticStr, Display,
)]
#[serde(rename_all = "lowercase")]
#[strum(serialize_all = "lowercase")]
pub enum ServiceMode {
    /// Incoming traffic is split between the local and the original
    /// service. The user-provided HTTP filter is used (if present),
    /// otherwise we fall back to an autogenerated one (see
    /// [`ServiceConfig::assemble`])
    #[default]
    Split,
}

// Manual impl because we want different user-facing docs
impl ValueEnum for ServiceMode {
    fn value_variants<'a>() -> &'a [Self] {
        Self::VARIANTS
    }

    fn to_possible_value(&self) -> Option<PossibleValue> {
        let name: &'static str = self.into();
        match self {
            ServiceMode::Split => Some(PossibleValue::new(name).help("Incoming traffic is split between the local and original services using HTTP filtering.
If no filter is provided, a header filter matching the regex `baggage: .*mirrord-session={session key}.*` will be used.")),
        }
    }
}

/// Specifies if this service should be run with `mirrord exec` or
/// `mirrord container`
#[derive(
    Clone, Debug, Serialize, Deserialize, PartialEq, Default, IntoStaticStr, Display, VariantArray,
)]
#[serde(rename_all = "lowercase")]
#[strum(serialize_all = "lowercase")]
pub enum RunType {
    #[default]
    Exec,
    Container,
}

/// Includes all information necessary to build the `mirrord` command
/// for this session.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields, rename_all = "lowercase")]
pub struct RunConfig {
    #[serde(default)]
    pub r#type: RunType,
    pub command: Vec<String>,
}

/// Default settings applied to all services.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Default)]
#[serde(deny_unknown_fields)]
pub struct CommonConfig {
    pub(crate) accept_invalid_certificates: Option<bool>,
    pub(crate) operator: Option<bool>,
    pub(crate) telemetry: Option<bool>,
}

/// Separate from [`mirrord_config::target::TargetConfig`] because we
/// use custom serde attributes for this that we don't want on the
/// other one.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize, Default)]
#[serde(deny_unknown_fields)]
pub struct TargetConfig {
    #[serde(
        default,
        deserialize_with = "mirrord_config::util::string_or_struct_option",
        serialize_with = "serialize_path"
    )]
    pub(crate) path: Option<Target>,
    pub(crate) namespace: Option<String>,
}

fn serialize_path<S>(path: &Option<Target>, serializer: S) -> Result<S::Ok, S::Error>
where
    S: serde::Serializer,
{
    match path {
        Some(target) => serializer.serialize_str(&target.to_string()),
        None => serializer.serialize_none(),
    }
}

impl From<TargetConfig> for mirrord_config::target::TargetConfig {
    fn from(value: TargetConfig) -> Self {
        Self {
            path: value.path,
            namespace: value.namespace,
        }
    }
}

/// Per-service configuration.
#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ServiceConfig {
    #[serde(default)]
    pub(crate) target: TargetConfig,

    #[serde(default)]
    pub(crate) env: EnvConfig,

    #[serde(default)]
    pub(crate) default_mode: ServiceMode,

    #[serde(default)]
    pub(crate) http_filter: HttpFilterConfig,

    #[serde(default)]
    pub(crate) ignore_ports: BTreeSet<u16>,

    pub(crate) run: RunConfig,
}

/// Resolved top-level `mirrord-up.yaml` configuration.
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(deny_unknown_fields)]
pub struct UpConfig {
    /// Settings applied to all services.
    #[serde(default)]
    pub common: CommonConfig,
    /// Per-service configurations keyed by service name.
    pub services: HashMap<String, ServiceConfig>,
}

impl ServiceConfig {
    /// Build a ([`LayerConfig`], [`RunConfig`]) pair for this service.
    fn assemble(self, defaults: &CommonConfig, key: EnvKey) -> (LayerConfig, RunConfig) {
        let mut cfg = LayerFileConfig {
            accept_invalid_certificates: defaults.accept_invalid_certificates,
            operator: defaults.operator,
            telemetry: defaults.telemetry,
            ..Default::default()
        }
        .generate_config(&mut ConfigContext::default())
        .unwrap();

        cfg.target = self.target.into();
        cfg.feature.env = self.env;

        match self.default_mode {
            ServiceMode::Split => {
                cfg.feature.network.incoming.mode = IncomingMode::Steal;

                cfg.feature.network.incoming.http_filter = if self.http_filter.is_filter_set() {
                    self.http_filter
                } else {
                    HttpFilterConfig {
                        header_filter: Some(format!(
                            "baggage: .*mirrord-session={}.*",
                            key.as_str()
                        )),
                        ..Default::default()
                    }
                };

                cfg.feature.split_queues = SplitQueuesConfig::all_wildcard(&key);
            }
        }

        cfg.feature.network.incoming.ignore_ports = self.ignore_ports.into_iter().collect();
        cfg.key = key;

        (cfg, self.run)
    }
}

/// All the information necessary to start and manage one of the child
/// mirrord sessions.
pub struct SubprocessCfg {
    /// The resolved layer configuration for this child process.
    pub config: LayerConfig,
    /// Name of the service this subprocess runs.
    pub service_name: String,
    /// How to run this service (exec vs container, and the command).
    pub run: RunConfig,
}

impl UpConfig {
    /// True unless the user opted out of telemetry.
    pub fn telemetry_enabled(&self) -> bool {
        self.common.telemetry.unwrap_or(true)
    }

    /// Produces an iterator of [`SubprocessCfg`]s, one per service defined in the configuration.
    pub fn service_configs<'a>(
        self,
        key: &'a EnvKey,
    ) -> impl Iterator<Item = SubprocessCfg> + use<'a> {
        let Self {
            common: defaults,
            services,
        } = self;

        services.into_iter().map(move |(service_name, svc)| {
            let (config, run) = svc.assemble(&defaults, key.clone());
            SubprocessCfg {
                config,
                service_name,
                run,
            }
        })
    }
}

impl CollectAnalytics for &CommonConfig {
    fn collect_analytics(&self, analytics: &mut Analytics) {
        let CommonConfig {
            accept_invalid_certificates,
            operator,
            telemetry,
        } = self;

        analytics.add(
            "accept_invalid_certificates",
            accept_invalid_certificates.is_some(),
        );
        analytics.add("operator", operator.is_some());
        analytics.add("telemetry", telemetry.is_some());
    }
}

impl CollectAnalytics for &UpConfig {
    fn collect_analytics(&self, analytics: &mut Analytics) {
        analytics.add("num_services", self.services.len());
        analytics.add("common_fields_used", &self.common);

        let mut count_target: u32 = 0;
        let mut count_env: u32 = 0;
        let mut count_default_mode: u32 = 0;
        let mut count_http_filter: u32 = 0;
        let mut count_ignore_ports: u32 = 0;

        let mut count_exec: u32 = 0;
        let mut count_container: u32 = 0;

        for svc in self.services.values() {
            let ServiceConfig {
                target,
                env,
                default_mode,
                http_filter,
                ignore_ports,
                run,
            } = svc;

            if *target != TargetConfig::default() {
                count_target += 1;
            }
            if *env != EnvConfig::default() {
                count_env += 1;
            }
            if *default_mode != ServiceMode::default() {
                count_default_mode += 1;
            }
            if http_filter.is_filter_set() {
                count_http_filter += 1;
            }
            if ignore_ports.is_empty().not() {
                count_ignore_ports += 1;
            }

            match run.r#type {
                RunType::Exec => count_exec += 1,
                RunType::Container => count_container += 1,
            }
        }

        let mut config_fields_used = Analytics::default();
        config_fields_used.add("target", count_target);
        config_fields_used.add("env", count_env);
        config_fields_used.add("default_mode", count_default_mode);
        config_fields_used.add("http_filter", count_http_filter);
        config_fields_used.add("ignore_ports", count_ignore_ports);
        analytics.add("config_fields_used", config_fields_used);

        let mut run_types = Analytics::default();
        run_types.add("exec", count_exec);
        run_types.add("container", count_container);
        analytics.add("run_types", run_types);
    }
}

#[cfg(test)]
#[allow(clippy::indexing_slicing)]
mod tests {
    use super::*;

    /// Helper: parse YAML into UpConfig via the two-layer config system.
    fn parse(yaml: &str) -> UpConfig {
        serde_yaml::from_str(yaml).unwrap()
    }

    #[test]
    fn defaults_applied_when_omitted() {
        let config = parse(
            r#"
            services:
              my-svc:
                run:
                  command: ["echo"]
            "#,
        );
        assert_eq!(config.common, Default::default(),);
    }

    #[test]
    fn defaults_overridden() {
        let config = parse(
            r#"
            common:
              accept_invalid_certificates: true
              operator: false
              telemetry: false
            services:
              my-svc:
                run:
                  command: ["echo"]
            "#,
        );
        assert_eq!(
            config.common,
            CommonConfig {
                accept_invalid_certificates: Some(true),
                operator: Some(false),
                telemetry: Some(false),
            }
        );
    }

    #[test]
    fn service_with_all_fields() {
        let config = parse(
            r#"
            services:
              web:
                target:
                  path: "deployment/web-app"
                  namespace: "staging"
                env:
                  override:
                    NODE_ENV: "development"
                default_mode: split
                http_filter:
                  header_filter: "x-session: local"
                run:
                  type: container
                  command: ["docker", "run", "-p", "8080:8080", "web:latest"]
            "#,
        );
        let svc = &config.services["web"];

        assert_eq!(
            svc.target.path.as_ref().unwrap().to_string(),
            "deployment/web-app"
        );
        assert_eq!(svc.target.namespace.as_deref(), Some("staging"));
        assert_eq!(
            svc.env.r#override.as_ref().unwrap()["NODE_ENV"],
            "development"
        );
        assert_eq!(svc.default_mode, ServiceMode::Split);
        assert_eq!(
            svc.http_filter.header_filter.as_deref(),
            Some("x-session: local")
        );
        assert_eq!(
            svc.run,
            RunConfig {
                r#type: RunType::Container,
                command: vec![
                    "docker".into(),
                    "run".into(),
                    "-p".into(),
                    "8080:8080".into(),
                    "web:latest".into(),
                ]
            }
        );
    }

    #[test]
    fn multiple_services_with_different_modes() {
        let config = parse(
            r#"
            services:
              svc-a:
                run:
                  type: exec
                  command: ["node", "a.js"]
              svc-b:
                run:
                  command: ["node", "b.js"]
            "#,
        );
        assert_eq!(config.services.len(), 2);

        for service in config.services.values() {
            assert_eq!(service.run.r#type, RunType::Exec);
        }
    }

    #[test]
    fn minimal_service_gets_defaults() {
        let config = parse(
            r#"
            services:
              svc:
                run:
                  command: ["echo"]
            "#,
        );
        let svc = &config.services["svc"];
        assert_eq!(svc.env, EnvConfig::default());
    }

    #[test]
    fn split_mode_injects_session_key_wildcard_queue_filters() {
        let config = parse(
            r#"
            common:
              operator: true
            services:
              worker:
                target:
                  path: "deployment/sqs-printer"
                run:
                  command: ["../target/debug/rust-sqs-printer"]
            "#,
        );

        let mut services = config
            .service_configs(&EnvKey::Provided("sqs-session".to_owned()))
            .collect::<Vec<_>>();
        assert_eq!(services.len(), 1);

        let service = services.pop().unwrap();
        assert_eq!(service.config.operator, Some(true));
        assert_eq!(
            service
                .config
                .feature
                .split_queues
                .splits()
                .iter()
                .map(|split| split.queue_id.as_str())
                .collect::<Vec<_>>(),
            vec!["*"; 6]
        );
        assert_eq!(
            service
                .config
                .feature
                .split_queues
                .sqs_jq_filters()
                .collect::<Vec<_>>(),
            vec![(
                "*",
                r#"(.MessageAttributes // {}) | [.. | select(type == "string" and contains("mirrord-session=sqs-session"))] | length > 0"#
            )]
        );
        assert_eq!(
            service
                .config
                .feature
                .split_queues
                .gcp_pubsub_jq_filters()
                .collect::<Vec<_>>(),
            vec![(
                "*",
                r#"(.attributes // {}) | [.. | select(type == "string" and contains("mirrord-session=sqs-session"))] | length > 0"#
            )]
        );
    }

    #[test]
    fn target_simple_string_form() {
        let config = parse(
            r#"
            services:
              svc:
                target:
                  path: "pod/my-pod/container/main"
                run:
                  command: ["echo"]
            "#,
        );
        assert_eq!(
            config.services["svc"]
                .target
                .path
                .as_ref()
                .unwrap()
                .to_string(),
            "pod/my-pod/container/main"
        );
    }

    // -- Error cases --

    #[test]
    fn error_missing_run() {
        let err = serde_yaml::from_str::<UpConfig>(
            r#"
            services:
              svc:
                default_mode: split
            "#,
        )
        .unwrap_err();
        assert!(
            err.to_string().contains("missing field `run`"),
            "expected error about missing run, got: {err}"
        );
    }

    #[test]
    fn error_invalid_mode() {
        let result: Result<UpConfig, _> = serde_yaml::from_str(
            r#"
            services:
              svc:
                default_mode: bogus
                run:
                  exec:
                    command: ["echo"]
            "#,
        );
        assert!(result.is_err());
    }

    // -- Analytics --

    fn collect(config: &UpConfig) -> serde_json::Value {
        let mut analytics = Analytics::default();
        config.collect_analytics(&mut analytics);
        serde_json::to_value(&analytics).unwrap()
    }

    #[test]
    fn analytics_minimal_config_reports_zero_counts() {
        let config = parse(
            r#"
            services:
              svc:
                run:
                  command: ["echo"]
            "#,
        );

        assert_json_diff::assert_json_eq!(
            collect(&config),
            serde_json::json!({
                "num_services": 1,
                "common_fields_used": {
                    "accept_invalid_certificates": false,
                    "operator": false,
                    "telemetry": false,
                },
                "config_fields_used": {
                    "target": 0,
                    "env": 0,
                    "default_mode": 0,
                    "http_filter": 0,
                    "ignore_ports": 0,
                },
                "run_types": {
                    "exec": 1,
                    "container": 0,
                },
            }),
        );
    }

    #[test]
    fn analytics_common_fields_tracked_individually() {
        let config = parse(
            r#"
            common:
              accept_invalid_certificates: true
              telemetry: false
            services:
              svc:
                run:
                  command: ["echo"]
            "#,
        );

        let result = collect(&config);
        assert_eq!(
            result["common_fields_used"]["accept_invalid_certificates"],
            true
        );
        assert_eq!(result["common_fields_used"]["operator"], false);
        assert_eq!(result["common_fields_used"]["telemetry"], true);
    }

    #[test]
    fn analytics_service_fields_aggregated_across_services() {
        // Three services: svc-a sets target + ignore_ports, svc-b sets env + http_filter,
        // svc-c sets target only. Counts should reflect the per-field population density
        // (e.g. `target: 2`, `http_filter: 1`).
        let config = parse(
            r#"
            services:
              svc-a:
                target:
                  path: "deployment/web-app"
                ignore_ports: [8080]
                run:
                  command: ["echo"]
              svc-b:
                env:
                  override:
                    KEY: "value"
                http_filter:
                  header_filter: "x-custom: foo"
                run:
                  type: container
                  command: ["docker", "run", "img"]
              svc-c:
                target:
                  path: "deployment/other"
                run:
                  command: ["echo"]
            "#,
        );

        let result = collect(&config);
        assert_eq!(result["num_services"], 3);
        assert_eq!(result["config_fields_used"]["target"], 2);
        assert_eq!(result["config_fields_used"]["env"], 1);
        assert_eq!(result["config_fields_used"]["http_filter"], 1);
        assert_eq!(result["config_fields_used"]["ignore_ports"], 1);
        assert_eq!(result["config_fields_used"]["default_mode"], 0);
        assert_eq!(result["run_types"]["exec"], 2);
        assert_eq!(result["run_types"]["container"], 1);
    }
}
