[package]
name = "layer-win"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
publish.workspace = true
keywords.workspace = true
categories.workspace = true
build = "build.rs"

[dependencies]
asdf-overlay-hook = "0.7.5"
once_cell = "1.21.3"
anyhow = "1.0.97"

[dependencies.windows]
version = "0.61"
features = [
    "Win32_Security", "Win32_System", "Win32_System_SystemServices"
]

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]