/// Runtime authentication method for a remote cluster.
///
/// Built from `ClusterAuthType` + any extra fields (region, eks cluster name).
#[derive(Debug, Clone)]
pub enum AuthMethod {
    /// Bearer token authentication (from Secret, auto-refreshed via TokenRequest API)
    BearerToken,

    /// mTLS client certificate authentication
    Mtls,

    /// AWS IAM authentication for EKS clusters.
    /// Tokens are generated locally using STS presigned URLs.
    AwsIam {
        /// AWS region of the EKS cluster
        region: String,
        /// EKS cluster name (for `x-k8s-aws-id` signed header)
        cluster_name: String,
    },

    /// Azure Workload Identity authentication for AKS clusters.
    /// Tokens are generated by exchanging the pod's projected SA token with Azure AD.
    AzureWorkloadIdentity {
        /// Azure AD tenant ID. If None, read from AZURE_TENANT_ID env var.
        tenant_id: Option<String>,
        /// Managed Identity client ID. If None, read from AZURE_CLIENT_ID env var.
        client_id: Option<String>,
    },
}

/// Credentials for connecting to a remote Kubernetes cluster.
///
/// Combined from cluster config (ConfigMap) and connection materials (Secret).
#[derive(Debug, Clone)]
pub struct ClusterCredentials {
    /// Logical cluster name (e.g., "staging-us-east")
    pub name: String,

    /// Kubernetes API server URL
    pub server: String,

    /// Namespace where the operator runs on this cluster
    pub namespace: String,

    /// CA certificate data (base64 encoded)
    pub ca_data: Option<String>,

    /// Authentication method used for this cluster
    pub auth_method: AuthMethod,

    /// Bearer token for authentication (None if using mTLS only or IAM)
    pub token: Option<String>,

    /// Client certificate chain for mTLS
    pub client_cert_pem: Option<Vec<u8>>,

    /// Client private key for mTLS
    pub client_key_pem: Option<Vec<u8>>,
}

impl ClusterCredentials {
    /// Check if this credentials has client certificate for mTLS.
    pub fn has_client_cert(&self) -> bool {
        self.client_cert_pem.is_some() && self.client_key_pem.is_some()
    }
}
