name: Build mirrord CLI
description: Build the mirrord CLI binary and upload as artifact

inputs:
  github-token:
    description: GitHub token for setup-protoc
    required: true

runs:
  using: composite
  steps:
    - uses: metalbear-co/setup-protoc@3ea1d70ac22caff0b66ed6cb37d5b7aadebd4623
      with:
        repo-token: ${{ inputs.github-token }}
    - uses: metalbear-co/setup-rust-toolchain@bb0a05a1b7e260b5081982438f974879f47940f4
      with:
        cache-shared-key: mirrord-${{ runner.os }}-${{ runner.arch }}
    - name: build mirrord CLI
      shell: bash
      run: cargo build --manifest-path=./Cargo.toml -p mirrord
    - name: upload mirrord CLI
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
      with:
        name: mirrord-artifacts
        path: |
          target/debug/mirrord
        if-no-files-found: error
