use base64::{Engine, prelude::BASE64_URL_SAFE_NO_PAD};
use rand::Rng;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::config::{
    ConfigContext, FromMirrordConfig, MirrordConfig, Result, from_env::FromEnv,
    source::MirrordConfigSource,
};

/// Environment variable name for the session key.
pub const MIRRORD_ENV_KEY: &str = "MIRRORD_KEY";

// Session key for traffic filtering.
//
// Distinguishes between user-provided keys (from CLI or config file)
// and auto-generated keys.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum EnvKey {
    // Key provided by user via CLI argument or config file.
    Provided(String),
    // Auto-generated random key when no key was provided.
    Generated(String),
}

impl EnvKey {
    /// Prefix used to mark auto-generated keys stored in [`ConfigContext`].
    ///
    /// When [`LayerFileConfig::from_path`] auto-generates a key (because neither CLI nor config
    /// file provided one), it must store the key in the context so that
    /// [`EnvKeyFileConfig::generate_config`] uses the *same* key. Without this, `generate_config`
    /// would generate a *different* key, causing a mismatch between the value used for template
    /// rendering (`{{ key }}`) and the final value in [`LayerConfig`].
    ///
    /// However, storing the auto-generated key in the context creates a problem: `generate_config`
    /// can't distinguish between a user-provided key and an auto-generated one - both just appear
    /// as values in `MIRRORD_ENV_KEY`. This marker solves that by prefixing auto-generated keys.
    /// When `generate_config` finds a key with this prefix, it strips the prefix and wraps the
    /// result in [`EnvKey::Generated`]; otherwise, it wraps it in [`EnvKey::Provided`].
    ///
    /// [`LayerFileConfig::from_path`]: crate::LayerFileConfig::from_path
    /// [`LayerConfig`]: crate::LayerConfig
    pub const AUTOGENERATED_MARKER: &str = "mirrord-internal-autogenerated";

    /// Returns the key value as a string slice.
    pub fn as_str(&self) -> &str {
        match self {
            EnvKey::Provided(s) | EnvKey::Generated(s) => s,
        }
    }

    /// Converts this key into a stable Kubernetes label value.
    ///
    /// Session keys are arbitrary strings, so this method hashes the key and encodes the digest in
    /// a form that satisfies [`Self::is_valid_kubernetes_label_value`].
    pub fn to_hashed_label_value(&self) -> String {
        let hash = BASE64_URL_SAFE_NO_PAD.encode(Sha256::digest(self.as_str().as_bytes()));
        // NB: First and last characters must be alphanumeric, hence the "h"s.
        format!("h{hash}h")
    }

    /// Returns whether this key is already a valid Kubernetes label value.
    ///
    /// Kubernetes label values must be at most 63 characters, may only contain alphanumeric
    /// characters, `-`, `_`, and `.`, and must start and end with an alphanumeric character.
    ///
    /// See the official Kubernetes reference:
    /// <https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set>
    pub fn is_valid_kubernetes_label_value(&self) -> bool {
        is_valid_kubernetes_label_value(self.as_str())
    }

    /// Returns whether this key was provided by the user (not auto-generated).
    pub fn is_provided(&self) -> bool {
        matches!(self, EnvKey::Provided(_))
    }

    /// Returns whether this key was auto-generated (not provided by the user).
    pub fn is_generated(&self) -> bool {
        matches!(self, EnvKey::Generated(_))
    }

    /// Returns the key value if it was provided by the user, `None` if auto-generated.
    pub fn provided(&self) -> Option<&str> {
        match self {
            EnvKey::Provided(s) => Some(s),
            EnvKey::Generated(_) => None,
        }
    }

    /// Returns the length to report in analytics.
    ///
    /// - 0 for auto-generated keys
    /// - Actual length for user-provided keys
    pub fn analytics_len(&self) -> usize {
        match self {
            EnvKey::Provided(s) => s.len(),
            EnvKey::Generated(_) => 0,
        }
    }

    /// Generates a short random hex key without any marker prefix.
    ///
    /// Uses a random value formatted as 5-character lowercase hex (0x00000 - 0xFFFFF). Short
    /// enough to fit inside Kubernetes label values (max 63 chars).
    ///
    /// Used by [`EnvKeyFileConfig::generate_config`] when no key was found in the context at all
    /// (i.e., when [`LayerFileConfig::from_path`] was never called, such as when using defaults).
    ///
    /// [`LayerFileConfig::from_path`]: crate::LayerFileConfig::from_path
    pub fn autogenerated() -> String {
        let value: u32 = rand::rng().random_range(0..0x100000);
        format!("{value:05x}")
    }

    /// Generates a short random hex key with [`AUTOGENERATED_MARKER`] prefix.
    ///
    /// Used by [`LayerFileConfig::from_path`] when auto-generating a key. The marker prefix
    /// allows [`EnvKeyFileConfig::generate_config`] to later identify this as an auto-generated
    /// key (see [`AUTOGENERATED_MARKER`] for details).
    ///
    /// [`LayerFileConfig::from_path`]: crate::LayerFileConfig::from_path
    /// [`AUTOGENERATED_MARKER`]: Self::AUTOGENERATED_MARKER
    pub fn autogenerated_with_marker() -> String {
        format!("{}{}", Self::AUTOGENERATED_MARKER, Self::autogenerated())
    }
}

fn is_valid_kubernetes_label_value(value: &str) -> bool {
    let bytes = value.as_bytes();

    if bytes.len() > 63 {
        return false;
    }

    let Some((first, last)) = bytes.first().zip(bytes.last()) else {
        return true;
    };

    first.is_ascii_alphanumeric()
        && last.is_ascii_alphanumeric()
        && bytes
            .iter()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
}

/// File configuration for the session key.
///
/// In the config file, the key is simply an optional string.
/// The resolution happens in [`MirrordConfig::generate_config`].
#[derive(Default, PartialEq, Eq, Clone, Debug, Serialize, Deserialize, JsonSchema)]
#[serde(transparent)]
pub struct EnvKeyFileConfig(pub Option<String>);

impl FromMirrordConfig for EnvKey {
    type Generator = EnvKeyFileConfig;
}

impl MirrordConfig for EnvKeyFileConfig {
    type Generated = EnvKey;

    fn generate_config(self, context: &mut ConfigContext) -> Result<Self::Generated> {
        let key_from_env: Option<String> = FromEnv::new(MIRRORD_ENV_KEY)
            .source_value(context)
            .transpose()?;

        let key = key_from_env
            .map(|key| {
                if let Some(key) = key.strip_prefix(EnvKey::AUTOGENERATED_MARKER) {
                    EnvKey::Generated(key.to_owned())
                } else {
                    EnvKey::Provided(key)
                }
            })
            .or(self.0.map(EnvKey::Provided))
            .unwrap_or_else(|| EnvKey::Generated(EnvKey::autogenerated()));

        Ok(key)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn autogenerated_key_is_5_hex_chars() {
        let key = EnvKey::autogenerated();
        assert_eq!(key.len(), 5, "key {key:?} should be exactly 5 characters");
        assert!(
            key.chars().all(|c| c.is_ascii_hexdigit()),
            "key {key:?} should only contain hex digits",
        );
    }

    #[test]
    fn autogenerated_with_marker_has_correct_prefix() {
        let key = EnvKey::autogenerated_with_marker();
        assert!(key.starts_with(EnvKey::AUTOGENERATED_MARKER));
        let suffix = &key[EnvKey::AUTOGENERATED_MARKER.len()..];
        assert_eq!(suffix.len(), 5);
    }

    #[test]
    fn hashed_label_value_is_valid_for_valid_and_invalid_keys() {
        for key in [
            "feature.foo",
            "feature/foo",
            "-feature",
            "feature-",
            "a".repeat(128).as_str(),
        ] {
            let label = EnvKey::Provided(key.to_owned()).to_hashed_label_value();

            assert!(
                is_valid_kubernetes_label_value(&label),
                "hashed label value {label:?} for key {key:?} should be a valid Kubernetes label value",
            );
        }
    }
}
