[package]
name = "medschool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "*"
syn = { version = "2", features = ["full", "extra-traits"]}
thiserror = "*"
