[package]
name = "mirrord-protover"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
publish.workspace = true
keywords.workspace = true
categories.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mirrord-protocol = { path = "../protocol"}
tokio.workspace = true
actix-codec.workspace = true
thiserror.workspace = true
futures.workspace = true
