export const strings = {
  common: {
    period: '.',
  },
  app: {
    title: 'mirrord',
    subtitle: 'Session Monitor',
    connected: 'Connected',
    disconnected: 'Disconnected',
    themeLight: 'Switch to light mode',
    themeDark: 'Switch to dark mode',
    settings: 'Settings',
    runningAs: 'Running as',
    searchPlaceholder: 'Search',
    emptyTitle: 'Select a session to get started',
    emptyBody:
      'Choose a session from the sidebar to see live activity, configuration, and intercepted traffic',
  },
  events: {
    waiting: 'Waiting for events...',
    clear: 'Clear events',
    search: 'Search events (Ctrl+F)',
    searchPlaceholder: 'Filter events...',
    countSuffix: 'events',
    noFilterMatch: 'No events match the current filter.',
    all: 'All Events',
    incoming: 'Incoming',
    outgoing: 'Outgoing',
    dns: 'DNS',
    fileOps: 'File Ops',
    unknownPath: '?',
    labels: {
      file: 'File',
      dns: 'DNS',
      http: 'HTTP',
      out: 'Out',
      info: 'Info',
    },
  },
  sidebar: {
    countSingular: 'session',
    countPlural: 'sessions',
    showSidebar: 'Show sidebar',
    hideSidebar: 'Hide sidebar',
    killAllTooltip: 'Stop all sessions',
    killAllTitle: 'Stop all sessions?',
    killAllDescription: (count: number) =>
      `This will end ${count} active mirrord ${count === 1 ? 'session' : 'sessions'}. This action cannot be undone.`,
    killAllButton: 'Stop all',
    cancel: 'Cancel',
    emptyTitle: 'No active sessions',
    emptyBody: 'Start mirrord to see sessions here',
    noSearchMatch: 'No sessions match your search.',
    clusterSide: 'Cluster-side',
    operatorError: 'Operator error',
    connecting: 'Connecting to operator…',
    reconnecting: 'Reconnecting to operator…',
    showingYours: 'Showing only your sessions.',
    connectOperator: 'Connect operator →',
    zeroSessions: '0 sessions · operator not connected',
  },
  session: {
    kill: 'Stop session',
    operator: 'Operator',
    direct: 'Direct',
    overview: 'Overview',
    eventsTab: 'Events',
    configTab: 'Config',
    chaosTab: 'Chaos Rules',
    sectionSession: 'Session',
    sectionPorts: 'Port Subscriptions',
    sectionProcesses: 'Processes',
    noPorts: 'No port subscriptions',
    fieldTarget: 'Target',
    fieldSessionId: 'Session ID',
    fieldVersion: 'Version',
    fieldKey: 'Key',
    columnName: 'Name',
    columnPid: 'PID',
    unknownProcess: 'unknown',
    processSingular: 'process',
    processPlural: 'processes',
    portSingular: 'port',
    portPlural: 'ports',
    eventsLabel: 'events',
  },
  badges: {
    joined: 'JOINED',
    preview: 'PREVIEW',
  },
  operatorDetail: {
    operatorBadge: 'operator',
    previewBadge: 'preview',
    readOnly: 'read-only',
  },
  namespacePicker: {
    namespace: 'Namespace',
    listError: "Couldn't list namespaces — type one to use it.",
  },
  emptyState: {
    title: 'No sessions yet',
    body: "Start a mirrord session and it'll appear here. Pick something below to get going, or join a teammate's session from the right-side extension.",
    runSession: 'Run a session',
    runSessionDesc:
      'Targets a deployment, runs your local process in its context. Drop this into a terminal.',
    previewEnv: 'Spin up a preview env',
    previewEnvDesc:
      'Spawns a long-lived preview pod from your image, shareable with teammates via a header key.',
    footer:
      'Sessions started anywhere on this machine, plus teammate sessions from the operator, show up automatically.',
  },
  errorBoundary: {
    title: 'Session Monitor crashed.',
    body: 'Please reload the page.',
  },
  funnel: {
    badge: 'mirrord for Teams',
    headline1: 'See what your team is mirroring,',
    headline2: 'and a lot more',
    body: 'Install the mirrord operator on your cluster to unlock preview environments, queue splitting, DB branching, and platform-level policies. Plus everything we ship next.',
    connect: 'Connect operator',
    whatUnlocks: 'What unlocks →',
  },
  settings: {
    description:
      'Preferences for this browser. Stored locally and never sent anywhere.',
    appearance: 'Appearance',
    appearanceHint: 'Match your OS, or pick a fixed theme.',
    analytics: 'Anonymous usage analytics',
    analyticsHint:
      'Click + scroll behavior only. No paths, hosts, headers, or bodies.',
  },
  operatorWizard: {
    title: 'Connect the mirrord operator',
    subtitle: 'Three steps, about 2 minutes.',
    iAlreadyHaveKey: 'I already have a key →',
    iveInstalledIt: "I've installed it →",
    done: 'Done',
    back: '← Back',
    copy: 'Copy',
    copied: 'Copied',
    openApp: 'Open app.metalbear.com',
    signupTitle: 'Sign up at app.metalbear.com',
    signupBody:
      'Create an account to get a license key. Your key activates the operator on any cluster you run mirrord against. 14-day trial, no card required.',
    bulletQueue: 'Queue splitting (SQS, Kafka, RabbitMQ)',
    bulletDb: 'Database branching (Postgres, MySQL, Mongo)',
    bulletPolicy: 'MirrordPolicy CRDs for platform guardrails',
    checkmark: '✓',
    installTitle: 'Install on your cluster',
    installBodyPrefix: 'Run these against your current kube context. Replace',
    yourKeyPlaceholder: '<YOUR_KEY>',
    installBodySuffix: ' with the license from step 1.',
    preferIac: 'Prefer Terraform or Argo CD?',
    installDocsLink: 'See the operator install docs',
    verifyTitle: 'Verify connection',
    verifyBody:
      'mirrord ui will detect the operator on your kube context. This usually takes a few seconds after install.',
    stuck: 'Stuck?',
    troubleshootingLink: 'Troubleshooting guide',
  },
  joinBar: {
    legacyExtensionPrefix:
      "Browser extension is installed but doesn't support one-click join yet. Open the extension popup and click Join on key",
    legacyExtensionSuffix: ', or update the extension.',
    installPrefix: 'Install the',
    extensionLink: 'mirrord browser extension',
    installSuffix:
      "to inject this session's matching header into your browser traffic and ride along.",
    install: 'Install',
    leave: 'Leave',
    joinedTitle: "You're joined.",
    joinedBody:
      "Outgoing browser requests now carry this session's matching header.",
    joinPrompt: 'Join this session to route your browser traffic through',
    joinPromptSuffix: '— the extension will inject the matching header.',
    currentlyJoinedPrefix: 'Currently joined to',
    currentlyJoinedSuffix: '; joining here will switch you over.',
  },
  chaos: {
    newRule: 'New rule',
    emptyTitle: 'No chaos rules yet',
    emptyBody: 'Add a rule to inject latency or connection errors into outgoing TCP traffic.',
    loadFailed: "Couldn't load chaos rules for this session.",
    columnName: 'Name',
    columnUpstream: 'Upstream',
    columnEffect: 'Effect',
    columnPercentage: '%',
    columnPriority: 'Priority',
    columnHits: 'Hits',
    edit: 'Edit rule',
    delete: 'Delete rule',
    deleteConfirmTitle: 'Delete this rule?',
    deleteConfirmDescription: (name: string) =>
      `This will stop applying "${name}" immediately. This action cannot be undone.`,
    cancel: 'Cancel',
    unnamed: 'Unnamed rule',
    formTitleCreate: 'New chaos rule',
    formTitleEdit: 'Edit chaos rule',
    fieldName: 'Name',
    fieldNamePlaceholder: 'Optional label for this rule',
    fieldUpstream: 'Upstream',
    fieldUpstreamPlaceholder: 'e.g. api.example.com:443',
    fieldUpstreamHint: 'The TCP host (and optional port) this rule targets.',
    fieldPercentage: 'Percentage',
    fieldPercentageHint: 'Chance (0-100) that matching traffic gets the effect applied.',
    fieldPriority: 'Priority',
    fieldPriorityHint: 'Higher priority wins when multiple rules match.',
    fieldSelectorType: 'Selector type',
    selectorTypeTcp: 'TCP',
    selectorTypeFs: 'File (coming soon)',
    fieldEffect: 'Effect',
    effectLatency: 'Latency',
    effectConnectionError: 'Connection error',
    fieldReadMs: 'Read latency (ms)',
    fieldWriteMs: 'Write latency (ms)',
    fieldJitterMs: 'Jitter (ms)',
    fieldErrorType: 'Error type',
    errorTypeReset: 'Connection reset',
    errorTypeTimedOut: 'Timed out',
    errorTypeRefused: 'Connection refused',
    fieldAfterMs: 'Apply after (ms)',
    selectorNoteTitle: 'More chaos types are coming',
    selectorNote: "Rules apply to outgoing TCP traffic today. Tell us what else you'd like to break.",
    latencyValidation: 'Set at least one of read or write latency.',
    upstreamRequired: 'Upstream is required.',
    submitCreate: 'Create rule',
    submitEdit: 'Save rule',
    submitting: 'Saving…',
    requestTypeButton: 'Request a fault type',
    requestTypeDialogTitle: 'Request a fualt type',
    requestTypeDialogDescription:
      "Tell us what kind of chaos rule you'd like to see (e.g. HTTP fault injection, DB query errors).",
    requestTypePlaceholder: 'e.g. Inject latency on outgoing HTTP requests to a specific host…',
    requestTypeSubmit: 'Send',
    requestTypeSent: "Thanks! We've noted your request.",
  },
} as const
