export const strings = {
  app: {
    title: 'mirrord',
    subtitle: 'Session Monitor',
    connected: 'Connected',
    disconnected: 'Disconnected',
    themeLight: 'Switch to light mode',
    themeDark: 'Switch to dark mode',
    settings: 'Settings',
    searchPlaceholder: 'Search',
    emptyTitle: 'Select a session to get started',
    emptyBody:
      'Choose a session from the sidebar to see live activity, configuration, and intercepted traffic',
  },
  events: {
    waiting: 'Waiting for events...',
    clear: 'Clear events',
    export: 'Download session log (.zip with JSON + HAR, credentials redacted)',
    search: 'Filter events',
    searchPlaceholder: 'Filter events...',
    countSuffix: 'events',
    all: 'All Events',
    incoming: 'Incoming',
    outgoing: 'Outgoing',
    dns: 'DNS',
    fileOps: 'File Ops',
    unknownPath: '?',
    detailNavHint: '↑↓ to move',
    inspector: 'Inspector',
    inspectorHeaders: 'Headers',
    inspectorBody: 'Body',
    inspectorDetails: 'Details',
    copyJson: 'Copy JSON',
    copyCurl: 'Copy as cURL',
    copied: 'Copied!',
    groupRepeats: 'Group repeats',
    live: 'live',
    errors: 'Errors',
    pause: 'Pause the stream',
    resume: 'Resume the stream',
    commandMenu: 'Command menu',
    waitingFiltered: 'Waiting for matching requests',
    waitingFilterHint: 'This session only intercepts requests matching',
    labels: {
      file: 'File',
      dns: 'DNS',
      http: 'HTTP',
      out: 'Out',
      info: 'Info',
    },
  },
  sidebar: {
    countSingular: 'session',
    countPlural: 'sessions',
    showSidebar: 'Show sidebar',
    hideSidebar: 'Hide sidebar',
    killAllTooltip: 'Stop all sessions',
    killAllTitle: 'Stop all sessions?',
    killAllDescription: (count: number) =>
      `This will end ${count} active mirrord ${count === 1 ? 'session' : 'sessions'}. This action cannot be undone.`,
    killAllButton: 'Stop all',
    cancel: 'Cancel',
    emptyTitle: 'No active sessions',
    emptyBody: 'Start mirrord to see sessions here',
  },
  session: {
    kill: 'Stop session',
    config: 'Session config',
    operator: 'Operator',
    direct: 'Direct',
    overview: 'Overview',
    eventsTab: 'Events',
    configTab: 'Config',
    sectionSession: 'Session',
    sectionPorts: 'Port Subscriptions',
    sectionProcesses: 'Processes',
    noPorts: 'No port subscriptions',
    fieldTarget: 'Target',
    fieldSessionId: 'Session ID',
    fieldVersion: 'Version',
    fieldKey: 'Key',
    columnName: 'Name',
    columnPid: 'PID',
    unknownProcess: 'unknown',
    processSingular: 'process',
    processPlural: 'processes',
    portSingular: 'port',
    portPlural: 'ports',
    eventsLabel: 'events',
  },
  operatorWizard: {
    title: 'Connect the mirrord operator',
    subtitle: 'Three steps, about 2 minutes.',
    iAlreadyHaveKey: 'I already have a key →',
    iveInstalledIt: "I've installed it →",
    done: 'Done',
    back: '← Back',
    copy: 'Copy',
    copied: 'Copied',
  },
  joinBar: {
    legacyExtensionPrefix:
      "Browser extension is installed but doesn't support one-click join yet. Open the extension popup and click Join on key",
    legacyExtensionSuffix: ', or update the extension.',
  },
} as const
