export const strings = {
  app: {
    title: 'mirrord',
    subtitle: 'Session Monitor',
    connected: 'Connected',
    disconnected: 'Disconnected',
    themeLight: 'Switch to light mode',
    themeDark: 'Switch to dark mode',
    settings: 'Settings',
    emptyTitle: 'Select a session to get started',
    emptyBody:
      'Choose a session from the sidebar to see live activity, configuration, and intercepted traffic',
  },
  events: {
    waiting: 'Waiting for events...',
    clear: 'Clear events',
    search: 'Search events (Ctrl+F)',
    searchPlaceholder: 'Filter events...',
    countSuffix: 'events',
    all: 'All Events',
    incoming: 'Incoming',
    outgoing: 'Outgoing',
    dns: 'DNS',
    fileOps: 'File Ops',
    unknownPath: '?',
    labels: {
      file: 'File',
      dns: 'DNS',
      http: 'HTTP',
      out: 'Out',
      info: 'Info',
    },
  },
  sidebar: {
    countSingular: 'session',
    countPlural: 'sessions',
    showSidebar: 'Show sidebar',
    hideSidebar: 'Hide sidebar',
    killAllTooltip: 'Stop all sessions',
    killAllTitle: 'Stop all sessions?',
    killAllDescription: (count: number) =>
      `This will end ${count} active mirrord ${count === 1 ? 'session' : 'sessions'}. This action cannot be undone.`,
    killAllButton: 'Stop all',
    cancel: 'Cancel',
    emptyTitle: 'No active sessions',
    emptyBody: 'Start mirrord to see sessions here',
  },
  session: {
    kill: 'Stop session',
    operator: 'Operator',
    direct: 'Direct',
    overview: 'Overview',
    eventsTab: 'Events',
    configTab: 'Config',
    sectionSession: 'Session',
    sectionPorts: 'Port Subscriptions',
    sectionProcesses: 'Processes',
    noPorts: 'No port subscriptions',
    fieldTarget: 'Target',
    fieldSessionId: 'Session ID',
    fieldVersion: 'Version',
    fieldKey: 'Key',
    columnName: 'Name',
    columnPid: 'PID',
    unknownProcess: 'unknown',
    processSingular: 'process',
    processPlural: 'processes',
    portSingular: 'port',
    portPlural: 'ports',
    eventsLabel: 'events',
  },
} as const
