[package]
name = "mirrord-vpn"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
publish.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
mirrord-protocol = { path = "../protocol" }

futures.workspace = true
k8s-openapi.workspace = true
kube.workspace = true
ipnet.workspace = true
paste = "1"
pnet_packet = "0.35"
semver.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "process"] }
tracing.workspace = true
tun2 = { workspace = true, features = ["async"] }
