name: Build mirrord CLI

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-mirrord-cli:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: ./.github/actions/build-mirrord-cli
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
