name: Check Typos

on:
  workflow_call:

permissions:
  contents: read

jobs:
  typos:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install typos
        uses: metalbear-co/install-action@62730e3d4f6bd81d824694e963e06d7153968c93
        with:
          tool: typos-cli
      - name: print typos version
        run: echo $(typos --version)
      - name: list markdown files
        run: echo $(git ls-files '*.md')
      - name: spell check markdown files
        run: typos --format brief $(git ls-files '*.md')
      - name: spell check mirrord/config crate
        run: typos --format brief $(git ls-files 'mirrord/config/*.rs')
