name: Check Lint

on:
  workflow_call:
    inputs:
      rust_toolchain:
        required: true
        type: string

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUSTUP_MAX_RETRIES: 10

jobs:
  lint:
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: rm rust-toolchain.toml
      - uses: metalbear-co/setup-rust-toolchain@a8d42d5aa259519dac1faeee20e37c1fb43453a3
        with:
          cache-shared-key: mirrord-${{ runner.os }}-${{ runner.arch }}
          toolchain: ${{ inputs.rust_toolchain }}
          components: rustfmt, clippy
          target: ${{ matrix.target }}
      - uses: metalbear-co/setup-protoc@3ea1d70ac22caff0b66ed6cb37d5b7aadebd4623
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: cargo fmt (run only on one platform)
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
        run: cargo fmt --all -- --check
      - if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
        run: cargo check -p mirrord-operator --features crd --target ${{ matrix.target }}
      - run: cargo clippy --workspace --lib --bins --all-features --tests -- "-Wclippy::indexing_slicing" -D warnings
  shear:
    name: "cargo shear"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: "Install cargo shear"
        uses: metalbear-co/install-action@c127aaa0fa8c555cbfb72bfa29b29a692d25d267 # v2.75.16
        with:
          tool: cargo-shear
      - run: ./scripts/cargo-shear.sh --deny-warnings
