name: Check Wizard Frontend Lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  wizard-frontend-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm install
        working-directory: ./packages/wizard
      - run: npm run lint
        working-directory: ./packages/wizard
