name: Release CI base images
on:
  push:
    branches: [main]
    paths:
      - 'ci/**'
      - 'ci/docker-bake.hcl'
      - '.github/workflows/ci-images.yaml'
  workflow_dispatch:

jobs:
  ci-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push CI images
        env:
          SHA: ${{ github.sha }}
        run: docker buildx bake -f ci/docker-bake.hcl ci-images --push
