name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main, v2.0 ]
  pull_request:
    branches: [ main, v2.0 ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: rustfmt, clippy
    # Needed for agent
    - run: sudo apt install libpcap-dev cmake
    - run: cargo fmt --all -- --check
    - run: cargo clippy -- -D warnings

  # test_mirrord_protocol:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, ubuntu-18.04, macos-12, macos-11, macos-10.15]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #       profile: minimal
  #       toolchain: nightly
  #   - run: cd mirrord-protocol && cargo test

  # test_agent:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #       profile: minimal
  #       toolchain: nightly
  #   - run: sudo apt install -y libpcap-dev cmake
  #   - run: sudo PATH=/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin:/usr/bin:/usr/sbin /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo test --manifest-path mirrord-agent/Cargo.toml 

  # test_agent_image:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build image
  #     run: docker build . --file mirrord-agent/Dockerfile

  
  # test_mirrord_layer:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, ubuntu-18.04, macos-12, macos-11, macos-10.15]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #       profile: minimal
  #       toolchain: nightly
  #   # For now, just evrify it compiles.
  #   - run: cargo +nightly build --manifest-path=mirrord-layer/Cargo.toml


  release_vscode_ext:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            extension: so
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64
          - os: ubuntu-18.04
            extension: so
            target: aarch64-unknown-linux-gnu
            code-target: linux-arm64
          - os: macos-11
            extension: dylib
            target: x86_64-apple-darwin
            code-target: darwin-x64
          - os: macos-11
            extension: dylib
            target: aarch64-apple-darwin
            code-target: darwin-arm64    
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    - run: npm install -g vsce
    - run: npm install typescript --save-dev
    - run: npm install -g esbuild
    - run: cargo +nightly build --release --manifest-path=mirrord-layer/Cargo.toml
    - run: mv target/release/libmirrord_layer.${{matrix.extension}} vscode-ext/
    - run: cd vscode-ext && npm install && tsc && cat package.json && vsce package  -o testpackage --target ${{matrix.code-target}}
