name: Release agent base images
on:
  workflow_call:
    outputs:
      agent_tag:
        description: "The generated Docker tag for the agent build image"
        value: ${{ jobs.builder.outputs.tag }}
      runtime_tag:
        description: "The generated Docker tag for the runtime image"
        value: ${{ jobs.runtime.outputs.tag }}
  workflow_dispatch:

jobs:
  builder:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tags.outputs.tag }}
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine test image version
        uses: ./ci/get-image-tag
        id: set-tags
        with:
          ci_changed: "true"
          target_dir: ci/agent-build
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./ci
          file: ci/agent-build/builder.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/metalbear-co/ci-agent-build:latest
            ghcr.io/metalbear-co/ci-agent-build:${{ steps.set-tags.outputs.tag }}

  runtime:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tags.outputs.tag }}
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine test image version
        uses: ./ci/get-image-tag
        id: set-tags
        with:
          ci_changed: "true"
          target_dir: ci/agent-build
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./ci
          file: ci/agent-build/runtime.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/metalbear-co/ci-agent-runtime:latest
            ghcr.io/metalbear-co/ci-agent-runtime:${{ steps.set-tags.outputs.tag }}
