name: IntelliJ Extension CI
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'intellij-ext/**'
  pull_request:
    branches: [main]
    paths:
      - 'intellij-ext/**'
jobs:
  build_intellij_plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Build Plugin
        env:
          CI_BUILD_PLUGIN: true
        run: |
          cd intellij-ext
          chmod +x ./gradlew
          ./gradlew buildPlugin