name: Update latest tag

on:
  workflow_dispatch:

jobs:
  update_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          # Get complete history
          fetch-depth: 0

      - name: Update major version and latest tags
        uses: metalbear-co/release-tracker-action@main
        env:
          # GitHub token to enable pushing tags
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Move "latest" tag
          update-latest: true
          # Don't update the vX.Y tags
          update-minor: false
