name: Test Windows

on:
  workflow_call:
    inputs:
      rust_toolchain:
        required: true
        type: string

permissions:
  contents: read

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"
  MIRRORD_TELEMETRY: false

jobs:
  windows-tests:
    runs-on: windows-latest
    env:
      MIRRORD_TESTS_USE_BINARY: ${{ github.workspace }}/target/debug/mirrord.exe
      MIRRORD_LAYER_FILE: ${{ github.workspace }}/target/debug/mirrord_layer_win.dll
    steps:
      - uses: actions/checkout@v4
      - run: Remove-Item rust-toolchain.toml
      - uses: metalbear-co/setup-rust-toolchain@a8d42d5aa259519dac1faeee20e37c1fb43453a3
        with:
          cache-shared-key: mirrord-${{ runner.os }}-${{ runner.arch }}
          components: rustfmt, clippy
          target: x86_64-pc-windows-msvc
          toolchain: ${{ inputs.rust_toolchain }}
      - run: |
          cd mirrord/layer-tests/tests/apps/outgoing
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/dns_resolve
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/rebind0
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/issue2058
          rustc issue2058.rs --out-dir target
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm install express
      - uses: actions/setup-python@v5
      - run: pip3 install --break-system-packages flask fastapi uvicorn[standard]
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: tests/go-e2e/go.sum
      - run: |
          go version
      - run: |
          . ./scripts/win_build_test_apps_utils.ps1
          Build-RepoGoApps -RepoRoot (Join-Path $pwd "mirrord/layer-tests/tests") -OutputPrefix "24"
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: false
      - run: |
          go version
      - run: |
          . ./scripts/win_build_test_apps_utils.ps1
          Build-RepoGoApps -RepoRoot (Join-Path $pwd "mirrord/layer-tests/tests") -OutputPrefix "25"
      - uses: actions/setup-go@v5
        with:
          go-version: "1.26"
          cache: false
      - run: |
          go version
      - run: |
          . ./scripts/win_build_test_apps_utils.ps1
          Build-RepoGoApps -RepoRoot (Join-Path $pwd "mirrord/layer-tests/tests") -OutputPrefix "26"
      - name: build layer
        run: cargo build -p mirrord-layer-win
      - name: build mirrord
        run: cargo build -p mirrord
      - name: mirrord layer integration tests
        run: |
          $ErrorActionPreference = "Stop"
          cargo test -p mirrord-layer-tests --no-default-features
      - name: run UT
        run: |
          $ErrorActionPreference = "Stop"
          cargo test -p mirrord -p mirrord-layer-win
