name: Test Integration

on:
  workflow_call:

permissions:
  contents: read

env:
  MIRRORD_TELEMETRY: false

jobs:
  integration-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # Checkout the mirrord repo.
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd
      - name: build mirrord tests image
        uses: docker/bake-action@82490499d2e5613fcead7e128237ef0b0ea210f7
        env:
          DOCKER_BUILD_RECORD_UPLOAD: "false"
          TESTS_IMAGE_TAGS: "mirrord-tests-image"
        with:
          source: .
          files: ci/docker-bake.hcl
          targets: mirrord-tests-image
          set: |
            mirrord-tests-image.output=type=docker,dest=${{ github.workspace }}/mirrord-tests-image.tar
      - name: load mirrord tests image
        run: docker load --input "${{ github.workspace }}/mirrord-tests-image.tar"
      - name: create intproxy logs dir
        run: mkdir -p "${{ runner.temp }}/intproxy_logs"
      - name: layer tests
        run: >-
          docker run --rm
          -v "${{ runner.temp }}/intproxy_logs:/tmp/intproxy_logs"
          mirrord-tests-image
      - name: unit tests (exclude e2e)
        run: >-
          docker run --rm
          -v "${{ runner.temp }}/intproxy_logs:/tmp/intproxy_logs"
          mirrord-tests-image
          cargo nextest run --workspace --exclude mirrord-tests
      - name: mirrord-kube UT
        run: >-
          docker run --rm
          -v "${{ runner.temp }}/intproxy_logs:/tmp/intproxy_logs"
          mirrord-tests-image
          cargo nextest run -p mirrord-kube --all-features
      - name: mirrord-operator UT
        run: >-
          docker run --rm
          -v "${{ runner.temp }}/intproxy_logs:/tmp/intproxy_logs"
          mirrord-tests-image
          cargo nextest run -p mirrord-operator --features "crd, client"
      - name: mirrord cli UT
        run: >-
          docker run --rm
          -v "${{ runner.temp }}/intproxy_logs:/tmp/intproxy_logs"
          mirrord-tests-image
          bash -lc 'touch wizard-frontend.tar.gz && cargo nextest run -p mirrord --features "wizard"'
      - name: save intproxy logs
        continue-on-error: true
        if: ${{ always() }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: intproxy_logs_linux
          path: ${{ runner.temp }}/intproxy_logs/linux
