name: Test Integration

on:
  workflow_call:

permissions:
  contents: read

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"
  MIRRORD_TELEMETRY: false

jobs:
  integration-tests:
    runs-on: ubuntu-24.04
    env:
      MIRRORD_TESTS_USE_BINARY: ${{ github.workspace }}/target/x86_64-unknown-linux-gnu/debug/mirrord
      MIRRORD_LAYER_FILE: ${{ github.workspace }}/target/x86_64-unknown-linux-gnu/debug/libmirrord_layer.so
    steps:
      - uses: actions/checkout@v4 # Checkout the mirrord repo.
      - uses: metalbear-co/setup-rust-toolchain@009cda47e1b529982a00627a40eda87b4215035a
        with:
          target: x86_64-unknown-linux-gnu
      - run: |
          cd mirrord/layer-tests/tests/apps/issue1123
          rustc issue1123.rs --out-dir target
      - run: |
          cd mirrord/layer-tests/tests/apps/issue1054
          rustc issue1054.rs --out-dir target
      - run: |
          cd mirrord/layer-tests/tests/apps/issue1458
          rustc issue1458.rs --out-dir target
      - run: |
          cd mirrord/layer-tests/tests/apps/issue1458portnot53
          rustc issue1458portnot53.rs --out-dir target
      - run: |
          cd mirrord/layer-tests/tests/apps/issue2058
          rustc issue2058.rs --out-dir target
      - run: |
          cd mirrord/layer-tests/tests/apps/issue2204
          rustc issue2204.rs --out-dir target
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm install express
      - uses: actions/setup-python@v5
      - run: pip3 install --break-system-packages flask fastapi uvicorn[standard]
      # don't use "cache" for other Gos since it will try to overwrite and have bad results.
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: tests/go-e2e/go.sum
      - run: |
          go version
      - run: | # Build Go test apps.
          cd mirrord/layer-tests/tests
          ../../../scripts/build_go_apps.sh 24
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: false
      - run: |
          go version
      - run: | # Build Go test apps.
          cd mirrord/layer-tests/tests
          ../../../scripts/build_go_apps.sh 25
      - uses: actions/setup-go@v5
        with:
          go-version: "1.26"
          cache: false
      - run: |
          go version
      - run: | # Build Go test apps.
          cd mirrord/layer-tests/tests
          ../../../scripts/build_go_apps.sh 26
      - run: |
          cd mirrord/layer-tests/tests/apps/fileops
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/outgoing
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/recv_from
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/dns_resolve
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/listen_ports
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/issue1776
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/issue1776portnot53
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/issue1899
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/issue2001
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/issue2438
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/issue3248
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/rebind0
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/dup_listen
          cargo build
      - run: |
          cd mirrord/layer-tests/tests/apps/double_listen
          cargo build
      - run: ./mirrord/layer-tests/tests/apps/dlopen_cgo/build_test_app.sh
      - run: ./scripts/build_c_apps.sh
      - run: cargo build --target x86_64-unknown-linux-gnu -p mirrord-layer -p mirrord
      - name: create dummy file to compile wizard feature
        run: touch wizard-frontend.tar.gz
      - name: layer tests
        run: cargo test --target x86_64-unknown-linux-gnu -p mirrord-layer-tests --no-default-features
      - name: unit tests
        run: >-
          cargo test --target x86_64-unknown-linux-gnu
          -p mirrord-layer-lib
          -p mirrord-layer
          -p mirrord-protocol
          -p mirrord-config
          -p mirrord-intproxy
          -p mirrord-auth
          -p mirrord-protocol-io
          -p mirrord-jaq
      - name: mirrord-kube UT
        run: cargo test --target x86_64-unknown-linux-gnu -p mirrord-kube --all-features
      - name: mirrord-operator UT
        run: cargo test --target x86_64-unknown-linux-gnu -p mirrord-operator --features "crd, client"
      - name: mirrord cli UT
        run: cargo test --target x86_64-unknown-linux-gnu -p mirrord --features "wizard"
      - name: save intproxy logs
        continue-on-error: true
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: intproxy_logs_linux
          path: /tmp/intproxy_logs/linux
