name: Test E2E

on:
  workflow_call:

permissions:
  contents: read

env:
  MIRRORD_TELEMETRY: false

jobs:
  e2e:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        container-runtime: ["docker", "containerd"]
    name: e2e
    env:
      MIRRORD_AGENT_RUST_LOG: "warn,mirrord=debug"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: ./.github/actions/e2e-setup
        with:
          container-runtime: ${{matrix.container-runtime}}
          tests-image-artifact-name: mirrord-tests-image
      - name: create e2e temp dir
        run: mkdir -p "${{ runner.temp }}/e2e-tmp"
      - name: download image
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: test
          path: /tmp
      - run: minikube image load /tmp/test.tar
      # run the cli tests only once, i.e. docker runtime only
      - name: Run cli E2E tests
        if: ${{ matrix.container-runtime == 'docker' }}
        run: >-
          docker run --rm --network host
          -e KUBECONFIG=/home/runner/.kube/config
          -e MIRRORD_AGENT_RUST_LOG="${{ env.MIRRORD_AGENT_RUST_LOG }}"
          -v "${HOME}/.kube:/home/runner/.kube:ro"
          -v "${HOME}/.minikube:/home/runner/.minikube:ro"
          -v "${{ runner.temp }}/e2e-tmp:/tmp"
          mirrord-tests-image
          cargo nextest run -p mirrord-tests --no-default-features --features cli --test-threads 6
      # This needs improving to prevent flakiness! e.g. examining output for progress messages
      # `sleep` is used here to give the wizard enough time to start before curl
      - run: >-
          docker run --rm --network host
          -e KUBECONFIG=/home/runner/.kube/config
          -e MIRRORD_AGENT_RUST_LOG="${{ env.MIRRORD_AGENT_RUST_LOG }}"
          -v "${HOME}/.kube:/home/runner/.kube:ro"
          -v "${HOME}/.minikube:/home/runner/.minikube:ro"
          -v "${{ runner.temp }}/e2e-tmp:/tmp"
          mirrord-tests-image
          bash -lc './target/debug/mirrord wizard & sleep 2 && curl localhost:3000'
      # By running the test of the targetless agent first, we prove it works on an empty cluster without any pods.
      - name: Run targetless E2E test
        run: >-
          docker run --rm --network host
          -e KUBECONFIG=/home/runner/.kube/config
          -e MIRRORD_AGENT_RUST_LOG="${{ env.MIRRORD_AGENT_RUST_LOG }}"
          -v "${HOME}/.kube:/home/runner/.kube:ro"
          -v "${HOME}/.minikube:/home/runner/.minikube:ro"
          -v "${{ runner.temp }}/e2e-tmp:/tmp"
          mirrord-tests-image
          cargo nextest run -p mirrord-tests --no-default-features --features targetless --test-threads 6 -E 'test(targetless)'
      # prepare argo rollouts
      - run: kubectl create namespace argo-rollouts
      - run: kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
      - name: Run all E2E tests
        run: >-
          docker run --rm --network host
          -e KUBECONFIG=/home/runner/.kube/config
          -e MIRRORD_AGENT_RUST_LOG="${{ env.MIRRORD_AGENT_RUST_LOG }}"
          -v "${HOME}/.kube:/home/runner/.kube:ro"
          -v "${HOME}/.minikube:/home/runner/.minikube:ro"
          -v "${{ runner.temp }}/e2e-tmp:/tmp"
          mirrord-tests-image
          bash -lc 'cargo nextest run -p mirrord-tests --no-default-features --features job --test-threads 6 && cargo nextest run -p mirrord-tests --no-default-features --features ephemeral --test-threads 6'
      - name: Collect logs
        if: ${{ failure() }}
        run: |
          find "${{ runner.temp }}/e2e-tmp" -type f -name 'mirrord-intproxy-*' -print -exec cat {} \;
          kubectl get all
          kubectl describe pods
          docker exec minikube find /var/log/pods -print -exec cat {} \;
